CREATE TABLE IF NOT EXISTS sr_embed_manager_url_cache (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    owner_module VARCHAR(60) NOT NULL,
    owner_type VARCHAR(60) NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    owner_field VARCHAR(60) NOT NULL DEFAULT 'body',
    source_url VARCHAR(1000) NOT NULL,
    canonical_url VARCHAR(1000) NOT NULL,
    canonical_url_hash CHAR(64) NOT NULL,
    embed_kind VARCHAR(30) NOT NULL DEFAULT 'internal_url',
    provider_key VARCHAR(60) NOT NULL DEFAULT '',
    render_variant VARCHAR(60) NOT NULL DEFAULT 'summary',
    target_module VARCHAR(60) NOT NULL DEFAULT '',
    target_type VARCHAR(60) NOT NULL DEFAULT '',
    target_id VARCHAR(80) NOT NULL DEFAULT '',
    target_cache_version VARCHAR(120) NOT NULL DEFAULT '',
    label_snapshot VARCHAR(255) NOT NULL DEFAULT '',
    summary_snapshot TEXT NULL,
    image_snapshot VARCHAR(500) NOT NULL DEFAULT '',
    image_snapshot_policy VARCHAR(30) NOT NULL DEFAULT 'none',
    target_state VARCHAR(30) NOT NULL DEFAULT '',
    resolver_state VARCHAR(30) NOT NULL DEFAULT '',
    cache_status VARCHAR(30) NOT NULL DEFAULT 'fresh',
    resolved_payload_json TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    last_resolved_at DATETIME NULL,
    last_render_checked_at DATETIME NULL,
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_sr_embed_manager_url_owner_hash (owner_module, owner_type, owner_id, owner_field, canonical_url_hash),
    KEY idx_sr_embed_manager_url_owner (owner_module, owner_type, owner_id, owner_field, cache_status, sort_order),
    KEY idx_sr_embed_manager_url_target (target_module, target_type, target_id, cache_status),
    KEY idx_sr_embed_manager_url_hash (canonical_url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS sr_embed_manager_refs;
