<?php

return [
    'google' => [
        'label' => 'Google',
        'authorization_url' => 'https://accounts.google.com/o/oauth2/v2/auth',
        'token_url' => 'https://oauth2.googleapis.com/token',
        'userinfo_url' => 'https://openidconnect.googleapis.com/v1/userinfo',
        'scopes' => ['openid', 'email', 'profile'],
        'subject_claim' => 'sub',
        'email_claim' => 'email',
        'email_scope' => 'email',
        'email_verified_claim' => 'email_verified',
        'display_name_claim' => 'name',
        'display_name_scope' => 'profile',
        'fallback_display_name_claim' => 'email',
        'sort_order' => 10,
    ],
    'kakao' => [
        'label' => 'Kakao',
        'authorization_url' => 'https://kauth.kakao.com/oauth/authorize',
        'token_url' => 'https://kauth.kakao.com/oauth/token',
        'userinfo_url' => 'https://kapi.kakao.com/v2/user/me',
        'scopes' => ['profile_nickname', 'account_email'],
        'scope_delimiter' => ',',
        'subject_claim' => 'id',
        'email_claim' => 'kakao_account.email',
        'email_scope' => 'account_email',
        'email_verified_claim' => 'kakao_account.is_email_verified',
        'display_name_claim' => 'kakao_account.profile.nickname',
        'display_name_scope' => 'profile_nickname',
        'fallback_display_name_claim' => 'properties.nickname',
        'sort_order' => 20,
    ],
    'naver' => [
        'label' => 'Naver',
        'authorization_url' => 'https://nid.naver.com/oauth2.0/authorize',
        'token_url' => 'https://nid.naver.com/oauth2.0/token',
        'userinfo_url' => 'https://openapi.naver.com/v1/nid/me',
        'scopes' => [],
        'subject_claim' => 'response.id',
        'email_claim' => 'response.email',
        'email_verified_claim' => '',
        'display_name_claim' => 'response.name',
        'fallback_display_name_claim' => 'response.nickname',
        'sort_order' => 30,
    ],
    'github' => [
        'label' => 'GitHub',
        'authorization_url' => 'https://github.com/login/oauth/authorize',
        'token_url' => 'https://github.com/login/oauth/access_token',
        'userinfo_url' => 'https://api.github.com/user',
        'email_url' => 'https://api.github.com/user/emails',
        'scopes' => ['read:user', 'user:email'],
        'subject_claim' => 'id',
        'email_claim' => 'email',
        'email_scope' => 'user:email',
        'email_verified_claim' => '',
        'display_name_claim' => 'name',
        'display_name_scope' => 'read:user',
        'fallback_display_name_claim' => 'login',
        'sort_order' => 40,
    ],
    'apple' => [
        'label' => 'Apple ID',
        'authorization_url' => 'https://appleid.apple.com/auth/authorize',
        'token_url' => 'https://appleid.apple.com/auth/token',
        'profile_source' => 'id_token',
        'scopes' => ['name', 'email'],
        'subject_claim' => 'sub',
        'email_claim' => 'email',
        'email_scope' => 'email',
        'email_verified_claim' => 'email_verified',
        'display_name_claim' => 'name',
        'display_name_scope' => 'name',
        'fallback_display_name_claim' => 'email',
        'sort_order' => 50,
    ],
];
