CREATE TABLE IF NOT EXISTS sr_logo_manager_logos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    position_key VARCHAR(120) NOT NULL,
    title VARCHAR(120) NOT NULL,
    alt_text VARCHAR(160) NOT NULL DEFAULT '',
    link_url VARCHAR(255) NOT NULL DEFAULT '',
    use_as_public_symbol TINYINT(1) NOT NULL DEFAULT 0,
    original_name VARCHAR(180) NOT NULL DEFAULT '',
    storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
    storage_key VARCHAR(255) NOT NULL,
    public_url VARCHAR(255) NOT NULL DEFAULT '',
    mime_type VARCHAR(80) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    width INT UNSIGNED NOT NULL DEFAULT 0,
    height INT UNSIGNED NOT NULL DEFAULT 0,
    checksum_sha256 CHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    sort_order INT NOT NULL DEFAULT 100,
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_logo_manager_logos_position_status (position_key, status, starts_at, ends_at, sort_order, id),
    KEY idx_sr_logo_manager_logos_storage (storage_driver, storage_key)
);

CREATE TABLE IF NOT EXISTS sr_logo_manager_icon_variants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    logo_id BIGINT UNSIGNED NOT NULL,
    batch_key VARCHAR(40) NOT NULL,
    variant_key VARCHAR(40) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    width INT UNSIGNED NOT NULL,
    height INT UNSIGNED NOT NULL,
    storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
    storage_key VARCHAR(255) NOT NULL,
    public_url VARCHAR(255) NOT NULL DEFAULT '',
    mime_type VARCHAR(80) NOT NULL DEFAULT 'image/png',
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    checksum_sha256 CHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_logo_manager_icon_variants_logo_variant_batch (logo_id, variant_key, batch_key),
    KEY idx_sr_logo_manager_icon_variants_logo_status (logo_id, status, purpose, width),
    KEY idx_sr_logo_manager_icon_variants_storage (storage_driver, storage_key)
);

CREATE TABLE IF NOT EXISTS sr_logo_manager_logo_usage_targets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    logo_id BIGINT UNSIGNED NOT NULL,
    layout_provider_key VARCHAR(40) NOT NULL,
    slot_key VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_logo_manager_usage_logo_provider_slot (logo_id, layout_provider_key, slot_key),
    KEY idx_sr_logo_manager_usage_lookup (layout_provider_key, slot_key, logo_id)
);
