CREATE TABLE IF NOT EXISTS sr_survey_forms (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_key VARCHAR(64) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    theme_key VARCHAR(40) NOT NULL DEFAULT '',
    skin_key VARCHAR(40) NOT NULL DEFAULT '',
    research_purpose TEXT NULL,
    target_population TEXT NULL,
    recruitment_method TEXT NULL,
    project_brief TEXT NULL,
    sponsor_name VARCHAR(190) NOT NULL DEFAULT '',
    research_region VARCHAR(120) NOT NULL DEFAULT '',
    research_language VARCHAR(60) NOT NULL DEFAULT '',
    fieldwork_method VARCHAR(120) NOT NULL DEFAULT '',
    sample_frame TEXT NULL,
    sample_method VARCHAR(190) NOT NULL DEFAULT '',
    target_sample_size INT UNSIGNED NULL,
    quota_policy TEXT NULL,
    response_rate_basis TEXT NULL,
    analysis_plan TEXT NULL,
    weighting_policy TEXT NULL,
    margin_error_note TEXT NULL,
    methodology_disclosure TEXT NULL,
    ethics_note TEXT NULL,
    sensitive_data_policy TEXT NULL,
    recontact_policy TEXT NULL,
    withdrawal_policy TEXT NULL,
    vendor_name VARCHAR(190) NOT NULL DEFAULT '',
    external_channel_policy TEXT NULL,
    invite_token_policy TEXT NULL,
    qa_status VARCHAR(30) NOT NULL DEFAULT 'unchecked',
    qa_note TEXT NULL,
    questionnaire_version INT UNSIGNED NOT NULL DEFAULT 1,
    revision_locked TINYINT(1) NOT NULL DEFAULT 0,
    estimated_minutes INT UNSIGNED NULL,
    organizer_name VARCHAR(120) NOT NULL DEFAULT '',
    contact_text VARCHAR(190) NOT NULL DEFAULT '',
    consent_required TINYINT(1) NOT NULL DEFAULT 0,
    consent_text TEXT NULL,
    privacy_notice TEXT NULL,
    anonymous_allowed TINYINT(1) NOT NULL DEFAULT 0,
    login_required TINYINT(1) NOT NULL DEFAULT 1,
    public_listed TINYINT(1) NOT NULL DEFAULT 1,
    robots_policy VARCHAR(30) NOT NULL DEFAULT 'auto',
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    response_limit_policy VARCHAR(30) NOT NULL DEFAULT 'per_survey_once',
    response_limit_period_seconds INT UNSIGNED NULL,
    member_group_keys_json LONGTEXT NULL,
    comments_enabled TINYINT(1) NOT NULL DEFAULT 0,
    secret_comments_enabled TINYINT(1) NOT NULL DEFAULT 0,
    reward_enabled TINYINT(1) NOT NULL DEFAULT 0,
    created_by_account_id BIGINT UNSIGNED NULL,
    updated_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_survey_forms_key (survey_key),
    KEY idx_sr_survey_forms_status_dates (status, starts_at, ends_at),
    KEY idx_sr_survey_forms_reward (reward_enabled),
    KEY idx_sr_survey_forms_qa (qa_status, revision_locked)
);

CREATE TABLE IF NOT EXISTS sr_survey_comments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_id BIGINT UNSIGNED NOT NULL,
    parent_comment_id BIGINT UNSIGNED NULL,
    thread_root_id BIGINT UNSIGNED NULL,
    depth TINYINT UNSIGNED NOT NULL DEFAULT 1,
    author_account_id BIGINT UNSIGNED NULL,
    author_public_name_snapshot VARCHAR(120) NOT NULL DEFAULT '',
    body_text TEXT NOT NULL,
    is_secret TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'published',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_sr_survey_comments_survey_status_id (survey_id, status, id),
    KEY idx_sr_survey_comments_thread (survey_id, status, thread_root_id, parent_comment_id, id),
    KEY idx_sr_survey_comments_parent (parent_comment_id),
    KEY idx_sr_survey_comments_author_id (author_account_id, id),
    KEY idx_sr_survey_comments_created (created_at, id)
);

CREATE TABLE IF NOT EXISTS sr_survey_questions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_id BIGINT UNSIGNED NOT NULL,
    question_key VARCHAR(64) NOT NULL,
    question_type VARCHAR(30) NOT NULL DEFAULT 'single_choice',
    prompt TEXT NOT NULL,
    analysis_note TEXT NULL,
    required TINYINT(1) NOT NULL DEFAULT 1,
    min_choices INT UNSIGNED NULL,
    max_choices INT UNSIGNED NULL,
    scale_points INT UNSIGNED NULL,
    scale_min_label VARCHAR(120) NOT NULL DEFAULT '',
    scale_max_label VARCHAR(120) NOT NULL DEFAULT '',
    number_unit VARCHAR(60) NOT NULL DEFAULT '',
    number_min DECIMAL(20,6) NULL,
    number_max DECIMAL(20,6) NULL,
    allow_decimal TINYINT(1) NOT NULL DEFAULT 0,
    allow_other TINYINT(1) NOT NULL DEFAULT 0,
    nonresponse_policy VARCHAR(30) NOT NULL DEFAULT 'none',
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_survey_questions_key (survey_id, question_key),
    KEY idx_sr_survey_questions_sort (survey_id, sort_order)
);

CREATE TABLE IF NOT EXISTS sr_survey_choices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    question_id BIGINT UNSIGNED NOT NULL,
    choice_key VARCHAR(64) NOT NULL,
    label VARCHAR(255) NOT NULL,
    is_other TINYINT(1) NOT NULL DEFAULT 0,
    is_nonresponse TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_survey_choices_key (question_id, choice_key),
    KEY idx_sr_survey_choices_sort (question_id, sort_order)
);

CREATE TABLE IF NOT EXISTS sr_survey_responses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'submitted',
    quality_status VARCHAR(30) NOT NULL DEFAULT 'accepted',
    quality_note TEXT NULL,
    consent_snapshot_json LONGTEXT NULL,
    metadata_snapshot_json LONGTEXT NULL,
    is_test TINYINT(1) NOT NULL DEFAULT 0,
    submitted_at DATETIME NOT NULL,
    rewarded_at DATETIME NULL,
    answer_snapshot_json LONGTEXT NULL,
    user_agent_hash VARCHAR(128) NULL,
    ip_hash VARCHAR(128) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_survey_responses_survey_account (survey_id, account_id, submitted_at),
    KEY idx_sr_survey_responses_account (account_id, submitted_at),
    KEY idx_sr_survey_responses_status (status, updated_at),
    KEY idx_sr_survey_responses_quality (quality_status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_survey_response_answers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    response_id BIGINT UNSIGNED NOT NULL,
    question_id BIGINT UNSIGNED NULL,
    question_key VARCHAR(64) NOT NULL,
    choice_id BIGINT UNSIGNED NULL,
    choice_key VARCHAR(64) NULL,
    answer_text TEXT NULL,
    answer_number DECIMAL(20,6) NULL,
    other_text TEXT NULL,
    answer_snapshot_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_survey_response_answers_response (response_id),
    KEY idx_sr_survey_response_answers_question (question_id),
    KEY idx_sr_survey_response_answers_choice (choice_id)
);

CREATE TABLE IF NOT EXISTS sr_survey_reward_policies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    reward_provider VARCHAR(30) NOT NULL DEFAULT 'ledger_asset',
    reward_module VARCHAR(40) NOT NULL,
    reward_code VARCHAR(120) NOT NULL,
    reward_amount INT NULL,
    dedupe_scope VARCHAR(20) NOT NULL DEFAULT 'per_survey',
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_survey_reward_policies_survey (survey_id, status, sort_order),
    KEY idx_sr_survey_reward_policies_provider (reward_provider, reward_module)
);

CREATE TABLE IF NOT EXISTS sr_survey_reward_grants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    survey_id BIGINT UNSIGNED NOT NULL,
    response_id BIGINT UNSIGNED NOT NULL,
    reward_policy_id BIGINT UNSIGNED NULL,
    account_id BIGINT UNSIGNED NULL,
    reward_provider VARCHAR(30) NOT NULL,
    reward_module VARCHAR(40) NOT NULL,
    reward_code VARCHAR(120) NOT NULL,
    reward_amount INT NULL,
    dedupe_scope VARCHAR(20) NOT NULL,
    dedupe_key VARCHAR(190) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    provider_reference_type VARCHAR(60) NULL,
    provider_reference_id VARCHAR(120) NULL,
    request_snapshot_json LONGTEXT NULL,
    result_snapshot_json LONGTEXT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    granted_at DATETIME NULL,
    failed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_survey_reward_grants_dedupe (dedupe_key),
    KEY idx_sr_survey_reward_grants_response (response_id),
    KEY idx_sr_survey_reward_grants_account (account_id, created_at),
    KEY idx_sr_survey_reward_grants_survey_status (survey_id, status),
    KEY idx_sr_survey_reward_grants_provider (reward_provider, reward_module)
);
