<?php

return [
    'GET /survey' => 'actions/home.php',
    'GET /survey/cover-image' => 'actions/cover-image.php',
    'GET /survey/ui-kit' => 'actions/ui-kit.php',
    'POST /survey/comment' => 'actions/comment.php',
    'POST /survey/comment/edit' => 'actions/comment-edit.php',
    'POST /survey/comment/delete' => 'actions/comment-delete.php',
    'GET /survey/*' => 'actions/view.php',
    'POST /survey/*' => 'actions/view.php',
    'GET /admin/surveys' => 'actions/admin-surveys.php',
    'POST /admin/surveys' => 'actions/admin-surveys.php',
    'GET /admin/surveys/groups' => 'actions/admin-groups.php',
    'POST /admin/surveys/groups' => 'actions/admin-groups.php',
    'GET /admin/surveys/comments' => 'actions/admin-comments.php',
    'POST /admin/surveys/comments' => 'actions/admin-comments.php',
    'GET /admin/surveys/responses' => 'actions/admin-responses.php',
    'POST /admin/surveys/responses' => 'actions/admin-responses.php',
    'GET /admin/surveys/reward-logs' => 'actions/admin-reward-logs.php',
    'GET /admin/surveys/statistics' => 'actions/admin-statistics.php',
    'GET /admin/surveys/export' => 'actions/admin-export.php',
    'GET /admin/surveys/settings' => 'actions/admin-settings.php',
    'POST /admin/surveys/settings' => 'actions/admin-settings.php',
    'GET /admin/surveys/notification-templates' => 'actions/admin-notification-templates.php',
    'POST /admin/surveys/notification-templates' => 'actions/admin-notification-templates.php',
    'GET /admin/surveys/embed-cache' => 'actions/admin-embed-cache.php',
    'POST /admin/surveys/embed-cache' => 'actions/admin-embed-cache.php',
];
