CREATE TABLE IF NOT EXISTS sr_coupon_definitions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    coupon_key VARCHAR(60) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    coupon_type VARCHAR(40) NOT NULL DEFAULT 'access',
    discount_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    discount_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
    discount_currency_code VARCHAR(3) NOT NULL DEFAULT '',
    target_type VARCHAR(60) NOT NULL DEFAULT 'all',
    target_id VARCHAR(80) NOT NULL DEFAULT '',
    refundable_policy VARCHAR(30) NOT NULL DEFAULT 'none',
    max_uses_per_issue INT UNSIGNED NOT NULL DEFAULT 1,
    valid_from DATETIME NULL,
    valid_until DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_definitions_key (coupon_key),
    KEY idx_sr_coupon_definitions_status_target (status, target_type, target_id)
);

CREATE TABLE IF NOT EXISTS sr_coupon_issues (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    issued_reason VARCHAR(255) NOT NULL DEFAULT '',
    issued_by_account_id BIGINT UNSIGNED NULL,
    claim_type VARCHAR(20) NOT NULL DEFAULT 'manual',
    claim_campaign_id BIGINT UNSIGNED NULL,
    claim_log_id BIGINT UNSIGNED NULL,
    nominal_price_amount BIGINT NOT NULL DEFAULT 0,
    nominal_price_currency_code VARCHAR(3) NOT NULL DEFAULT '',
    asset_reference_module VARCHAR(60) NOT NULL DEFAULT '',
    asset_reference_type VARCHAR(80) NOT NULL DEFAULT '',
    asset_reference_id VARCHAR(120) NOT NULL DEFAULT '',
    claim_snapshot_json TEXT NULL,
    issued_at DATETIME NOT NULL,
    expires_at DATETIME NULL,
    used_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_coupon_issues_account_status (account_id, status, expires_at, id),
    KEY idx_sr_coupon_issues_definition (coupon_definition_id, status, id),
    KEY idx_sr_coupon_issues_claim_campaign (claim_campaign_id, claim_log_id, id)
);

CREATE TABLE IF NOT EXISTS sr_coupon_redemptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    coupon_issue_id BIGINT UNSIGNED NOT NULL,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    target_type VARCHAR(60) NOT NULL,
    target_id VARCHAR(80) NOT NULL DEFAULT '',
    reference_module VARCHAR(60) NOT NULL DEFAULT '',
    reference_type VARCHAR(80) NOT NULL DEFAULT '',
    reference_id VARCHAR(120) NOT NULL DEFAULT '',
    amount BIGINT NOT NULL DEFAULT 0,
    currency_code VARCHAR(3) NOT NULL DEFAULT '',
    asset_unit VARCHAR(40) NOT NULL DEFAULT '',
    policy_summary VARCHAR(255) NOT NULL DEFAULT '',
    priced_at DATETIME NULL,
    target_snapshot_json TEXT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'redeemed',
    redeemed_at DATETIME NOT NULL,
    refunded_at DATETIME NULL,
    refunded_by_account_id BIGINT UNSIGNED NULL,
    refund_note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_redemptions_dedupe (dedupe_key),
    KEY idx_sr_coupon_redemptions_account (account_id, redeemed_at),
    KEY idx_sr_coupon_redemptions_issue (coupon_issue_id, id),
    KEY idx_sr_coupon_redemptions_reference (reference_module, reference_type, reference_id)
);

CREATE TABLE IF NOT EXISTS sr_coupon_claim_campaigns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_key VARCHAR(60) NOT NULL,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    claim_type VARCHAR(20) NOT NULL DEFAULT 'free',
    price_amount INT UNSIGNED NULL,
    price_currency_code VARCHAR(3) NOT NULL DEFAULT '',
    allowed_asset_modules_json TEXT NULL,
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    issue_expires_in_days INT UNSIGNED NULL,
    issue_expires_at DATETIME NULL,
    total_claim_limit INT UNSIGNED NULL,
    per_account_limit INT UNSIGNED NOT NULL DEFAULT 1,
    visibility VARCHAR(20) NOT NULL DEFAULT 'hidden',
    exposure_surfaces_json TEXT NOT NULL,
    login_required TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_claim_campaigns_key (campaign_key),
    KEY idx_sr_coupon_claim_campaigns_public (status, visibility, starts_at, ends_at, id),
    KEY idx_sr_coupon_claim_campaigns_definition (coupon_definition_id, status, id)
);

CREATE TABLE IF NOT EXISTS sr_coupon_claim_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id BIGINT UNSIGNED NOT NULL,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    coupon_issue_id BIGINT UNSIGNED NULL,
    claim_source VARCHAR(40) NOT NULL DEFAULT 'coupon_zone',
    source_context_json TEXT NOT NULL,
    payment_reference_module VARCHAR(60) NOT NULL DEFAULT '',
    payment_reference_type VARCHAR(80) NOT NULL DEFAULT '',
    payment_reference_id VARCHAR(120) NOT NULL DEFAULT '',
    asset_reference_module VARCHAR(60) NOT NULL DEFAULT '',
    asset_reference_type VARCHAR(80) NOT NULL DEFAULT '',
    asset_reference_id VARCHAR(120) NOT NULL DEFAULT '',
    dedupe_key VARCHAR(255) NOT NULL,
    dedupe_hash CHAR(64) NOT NULL,
    occupying_account_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'reserved',
    reserved_until DATETIME NULL,
    failure_code VARCHAR(60) NOT NULL DEFAULT '',
    failure_message VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    issued_at DATETIME NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_claim_logs_dedupe (campaign_id, dedupe_hash),
    UNIQUE KEY uq_sr_coupon_claim_logs_issue (coupon_issue_id),
    UNIQUE KEY uq_sr_coupon_claim_logs_account_once (campaign_id, occupying_account_id),
    KEY idx_sr_coupon_claim_logs_campaign_status (campaign_id, status, reserved_until, id),
    KEY idx_sr_coupon_claim_logs_account (account_id, status, id)
);
