CREATE TABLE IF NOT EXISTS sr_payment_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dedupe_key VARCHAR(190) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    subject_module VARCHAR(60) NOT NULL,
    subject_type VARCHAR(80) NOT NULL,
    subject_id VARCHAR(120) NOT NULL,
    payment_kind VARCHAR(40) NOT NULL DEFAULT 'purchase',
    status VARCHAR(30) NOT NULL DEFAULT 'paid',
    payable_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    settlement_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    settlement_currency VARCHAR(3) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    snapshot_json TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    cancelled_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_payment_records_dedupe (dedupe_key),
    KEY idx_sr_payment_records_account (account_id, created_at),
    KEY idx_sr_payment_records_subject (subject_module, subject_type, subject_id),
    KEY idx_sr_payment_records_status (status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_payment_record_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    payment_record_id BIGINT UNSIGNED NOT NULL,
    item_kind VARCHAR(40) NOT NULL,
    owner_module VARCHAR(60) NOT NULL,
    reference_type VARCHAR(80) NOT NULL,
    reference_id VARCHAR(120) NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    currency_code VARCHAR(3) NOT NULL DEFAULT '',
    reversible TINYINT(1) NOT NULL DEFAULT 0,
    reversal_status VARCHAR(30) NOT NULL DEFAULT 'none',
    snapshot_json TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_payment_record_item_ref (payment_record_id, item_kind, owner_module, reference_type, reference_id),
    KEY idx_sr_payment_record_items_payment (payment_record_id, id),
    KEY idx_sr_payment_record_items_reference (owner_module, reference_type, reference_id),
    KEY idx_sr_payment_record_items_reversal (reversal_status, updated_at)
);
