CREATE TABLE IF NOT EXISTS sr_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NULL,
    audience VARCHAR(30) NOT NULL DEFAULT 'account',
    title VARCHAR(160) NOT NULL,
    body_text TEXT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    link_url VARCHAR(255) NOT NULL DEFAULT '',
    source_module_key VARCHAR(60) NOT NULL DEFAULT '',
    event_key VARCHAR(120) NOT NULL DEFAULT '',
    metadata_json TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    read_at DATETIME NULL,
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_notifications_account (account_id, status, read_at, id),
    KEY idx_sr_notifications_audience (audience, status, id),
    KEY idx_sr_notifications_event (source_module_key, event_key)
);

CREATE TABLE IF NOT EXISTS sr_notification_deliveries (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    notification_id BIGINT UNSIGNED NOT NULL,
    channel VARCHAR(30) NOT NULL,
    recipient VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    provider_message_id VARCHAR(120) NOT NULL DEFAULT '',
    error_message VARCHAR(255) NOT NULL DEFAULT '',
    attempted_at DATETIME NULL,
    locked_at DATETIME NULL,
    locked_by VARCHAR(80) NOT NULL DEFAULT '',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_notification_deliveries_notification (notification_id),
    KEY idx_sr_notification_deliveries_channel_status (channel, status, id),
    KEY idx_sr_notification_deliveries_runner (status, next_attempt_at, locked_at, id)
);

CREATE TABLE IF NOT EXISTS sr_notification_push_endpoints (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NOT NULL,
    provider_key VARCHAR(30) NOT NULL,
    recipient_type VARCHAR(40) NOT NULL DEFAULT 'personal',
    endpoint_ciphertext TEXT NOT NULL,
    endpoint_fingerprint CHAR(64) NOT NULL,
    recipient_label VARCHAR(120) NOT NULL DEFAULT '',
    recipient_masked VARCHAR(120) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    key_version VARCHAR(30) NOT NULL DEFAULT 'v1',
    verified_at DATETIME NULL,
    disabled_at DATETIME NULL,
    last_used_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_notification_push_endpoint_fingerprint (provider_key, endpoint_fingerprint),
    KEY idx_sr_notification_push_endpoints_account (account_id, provider_key, status, id)
);

CREATE TABLE IF NOT EXISTS sr_notification_reads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    notification_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    read_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_notification_reads (notification_id, account_id),
    KEY idx_sr_notification_reads_account (account_id, read_at)
);

CREATE TABLE IF NOT EXISTS sr_admin_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(160) NOT NULL,
    body_text TEXT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'info',
    source_module_key VARCHAR(60) NOT NULL DEFAULT '',
    event_key VARCHAR(120) NOT NULL DEFAULT '',
    target_type VARCHAR(80) NOT NULL DEFAULT '',
    target_id VARCHAR(80) NOT NULL DEFAULT '',
    action_url VARCHAR(255) NOT NULL DEFAULT '',
    permission_path VARCHAR(120) NOT NULL DEFAULT '',
    permission_action VARCHAR(20) NOT NULL DEFAULT 'view',
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    dedupe_key VARCHAR(190) NOT NULL DEFAULT '',
    occurrence_count INT UNSIGNED NOT NULL DEFAULT 1,
    created_by_account_id BIGINT UNSIGNED NULL,
    processed_by_account_id BIGINT UNSIGNED NULL,
    processed_at DATETIME NULL,
    archived_at DATETIME NULL,
    last_occurred_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_admin_notifications_dedupe (dedupe_key),
    KEY idx_sr_admin_notifications_status (status, severity, updated_at, id),
    KEY idx_sr_admin_notifications_permission (permission_path, permission_action, status, id),
    KEY idx_sr_admin_notifications_source (source_module_key, event_key, target_type, target_id)
);

CREATE TABLE IF NOT EXISTS sr_admin_notification_reads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    notification_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    read_at DATETIME NULL,
    acknowledged_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_admin_notification_reads (notification_id, account_id),
    KEY idx_sr_admin_notification_reads_account (account_id, read_at, acknowledged_at),
    KEY idx_sr_admin_notification_reads_notification (notification_id)
);

CREATE TABLE IF NOT EXISTS sr_notification_event_templates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    module_key VARCHAR(60) NOT NULL,
    event_key VARCHAR(120) NOT NULL,
    title_template VARCHAR(160) NOT NULL,
    body_template TEXT NULL,
    link_template VARCHAR(255) NOT NULL DEFAULT '',
    channels_json TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_notification_event_templates_key (module_key, event_key),
    KEY idx_sr_notification_event_templates_status (status, module_key, event_key)
);

INSERT INTO sr_notification_event_templates
    (module_key, event_key, title_template, body_template, link_template, channels_json, status, created_at, updated_at)
VALUES
    ('point', 'transaction.grant', '포인트가 지급되었습니다.', '변동 금액: {amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.refund', '포인트가 복원되었습니다.', '변동 금액: {amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.exchange_in', '포인트가 환전 입금되었습니다.', '변동 금액: {amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.use', '포인트가 사용되었습니다.', '변동 금액: -{amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.expire', '포인트가 만료되었습니다.', '변동 금액: -{amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.exchange_out', '포인트가 환전 출금되었습니다.', '변동 금액: -{amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.exchange_fee', '포인트 환전 수수료가 차감되었습니다.', '변동 금액: -{amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.adjustment.increase', '포인트가 증가했습니다.', '변동 금액: {amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('point', 'transaction.adjustment.decrease', '포인트가 감소했습니다.', '변동 금액: -{amount_abs}포인트\n변동 후 잔액: {balance_after}포인트\n사유: {reason}\n발생 시각: {created_at}', '/account/points', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.grant', '적립금이 지급되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.refund', '적립금이 복원되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.exchange_in', '적립금이 환전 입금되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.use', '적립금이 사용되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.expire', '적립금이 만료되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.exchange_out', '적립금이 환전 출금되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.exchange_fee', '적립금 환전 수수료가 차감되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.withdraw', '적립금 출금이 처리되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.reclaim', '적립금이 회수되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.adjustment.increase', '적립금이 증가했습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('reward', 'transaction.adjustment.decrease', '적립금이 감소했습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/rewards', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.deposit', '예치금이 입금되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.refund', '예치금이 복원되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.exchange_in', '예치금이 환전 입금되었습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.use', '예치금이 사용되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.exchange_out', '예치금이 환전 출금되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.exchange_fee', '예치금 환전 수수료가 차감되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.withdraw', '예치금 출금이 처리되었습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.adjustment.increase', '예치금이 증가했습니다.', '변동 금액: {amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('deposit', 'transaction.adjustment.decrease', '예치금이 감소했습니다.', '변동 금액: -{amount_abs}원\n변동 후 잔액: {balance_after}원\n사유: {reason}\n발생 시각: {created_at}', '/account/deposits', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'issue.created', '쿠폰·이용권이 발급되었습니다.', '쿠폰·이용권: {coupon_title}\n사유: {issued_reason}\n사용 가능 횟수: {max_uses_per_issue}회\n발급 시각: {issued_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'redemption.redeemed', '쿠폰·이용권이 사용되었습니다.', '쿠폰·이용권: {coupon_title}\n사용 횟수: {used_count}/{max_uses_per_issue}회\n상태: {status_label}\n사용 시각: {created_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'redemption.refunded', '쿠폰·이용권 사용이 환불되었습니다.', '쿠폰·이용권: {coupon_title}\n사용 횟수: {used_count}/{max_uses_per_issue}회\n상태: {status_label}\n환불 시각: {refunded_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'issue.refunded', '쿠폰·이용권 발급이 환불되었습니다.', '쿠폰·이용권: {coupon_title}\n상태: {status_label}\n환불 시각: {refunded_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'issue.status_updated', '쿠폰·이용권 상태가 변경되었습니다.', '쿠폰·이용권: {coupon_title}\n상태: {status_label}\n발급 시각: {issued_at}\n만료 시각: {expires_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('coupon', 'issue.definition_disabled', '쿠폰·이용권 사용이 중지되었습니다.', '쿠폰·이용권: {coupon_title}\n운영상 사유로 해당 쿠폰·이용권을 더 이상 사용할 수 없습니다.\n발급 시각: {issued_at}', '/account/coupons', '["site"]', 'active', NOW(), NOW()),
    ('content', 'comment.created', '새 콘텐츠 댓글이 등록되었습니다.', '{member_name}님이 회원님의 콘텐츠에 댓글을 남겼습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('content', 'comment.mention', '콘텐츠 댓글에서 회원님을 언급했습니다.', '{member_name}님이 콘텐츠 댓글에서 회원님을 언급했습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('content', 'followed_author.content_created', '{member_name}님이 새 콘텐츠를 등록했습니다.', '콘텐츠: {content_title}\n등록 시각: {created_at}\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('community', 'comment.created', '새 댓글이 등록되었습니다.', '{member_name}님이 회원님의 게시글에 댓글을 남겼습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('community', 'comment.mention', '댓글에서 회원님을 언급했습니다.', '{member_name}님이 커뮤니티 댓글에서 회원님을 언급했습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('community', 'followed_author.post_created', '{member_name}님이 새 게시글을 등록했습니다.', '게시판: {board_title}\n게시글: {post_title}\n등록 시각: {created_at}\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('quiz', 'comment.mention', '퀴즈 댓글에서 회원님을 언급했습니다.', '{member_name}님이 퀴즈 댓글에서 회원님을 언급했습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('survey', 'comment.mention', '설문 댓글에서 회원님을 언급했습니다.', '{member_name}님이 설문 댓글에서 회원님을 언급했습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('reaction', 'target.reacted', '새 리액션이 등록되었습니다.', '{member_name}님이 {target_label}에 {reaction_label} 리액션을 남겼습니다.\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('community', 'attachment.publisher_reward.granted', '첨부 다운로드 리워드가 지급되었습니다.', '지급 금액: {amount}{asset}\n\n{link_url}', '{link_url}', '["site"]', 'active', NOW(), NOW()),
    ('notification', 'member_push_endpoint.connected', '외부 푸시 수신처가 연결되었습니다.', '개인 외부 수신처가 알림 푸시에 연결되었습니다.', '/account/notifications', '["site"]', 'active', NOW(), NOW()),
    ('notification', 'member_push_endpoint.disabled', '외부 푸시 수신처가 해제되었습니다.', '개인 외부 수신처가 알림 푸시에서 해제되었습니다.', '/account/notifications', '["site"]', 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE
    title_template = VALUES(title_template),
    body_template = VALUES(body_template),
    link_template = VALUES(link_template),
    channels_json = VALUES(channels_json),
    updated_at = VALUES(updated_at);
