<?php

return [
    'name' => '알림',
    'version' => '2026.07.003',
    'type' => 'module',
    'description' => '사이트 알림과 알림 발송 작업을 관리합니다.',
    'admin' => [
        'category' => 'operation',
        'category_label' => '운영',
        'category_order' => 40,
        'menu_order' => 10,
        'icon' => ['type' => 'symbol', 'name' => 'bell'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin'],
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'retention-targets.php',
            'operational-status.php',
            'menu-links.php',
            'privacy-export.php',
            'privacy-cleanup.php',
            'notification-events.php',
            'admin-notification-events.php',
        ],
    ],
    'settings' => [
        'email_channel_enabled' => true,
        'email_transport' => 'php_mail',
        'email_from_email' => '',
        'email_from_name' => '',
        'email_smtp_host' => '',
        'email_smtp_port' => 587,
        'email_smtp_encryption' => 'tls',
        'email_smtp_username' => '',
        'email_smtp_password' => '',
        'email_timeout_seconds' => 10,
        'email_http_api_endpoint' => '',
        'email_http_api_bearer_token' => '',
        'external_push_enabled' => false,
        'slack_webhook_enabled' => true,
        'slack_member_push_enabled' => false,
        'slack_webhook_url' => '',
        'slack_channel_label' => '운영 알림',
        'discord_webhook_enabled' => false,
        'discord_member_push_enabled' => false,
        'discord_webhook_url' => '',
        'discord_channel_label' => '운영 알림',
        'telegram_bot_enabled' => false,
        'telegram_member_push_enabled' => false,
        'telegram_bot_token' => '',
        'telegram_chat_id' => '',
        'telegram_channel_label' => '운영 알림',
        'external_push_failure_policy' => 'retry',
        'delivery_web_runner_enabled' => true,
        'delivery_web_runner_interval_seconds' => 60,
        'delivery_web_runner_batch_size' => 1,
        'delivery_manual_batch_size' => 10,
        'delivery_cli_batch_size' => 20,
        'delivery_max_attempts' => 5,
        'delivery_lock_timeout_seconds' => 300,
        'delivery_last_web_runner_at' => '',
    ],
];
