ALTER TABLE {{SR_TABLE_PREFIX}}survey_forms
    ADD COLUMN project_brief TEXT NULL AFTER recruitment_method,
    ADD COLUMN sponsor_name VARCHAR(190) NOT NULL DEFAULT '' AFTER project_brief,
    ADD COLUMN research_region VARCHAR(120) NOT NULL DEFAULT '' AFTER sponsor_name,
    ADD COLUMN research_language VARCHAR(60) NOT NULL DEFAULT '' AFTER research_region,
    ADD COLUMN fieldwork_method VARCHAR(120) NOT NULL DEFAULT '' AFTER research_language,
    ADD COLUMN sample_frame TEXT NULL AFTER fieldwork_method,
    ADD COLUMN sample_method VARCHAR(190) NOT NULL DEFAULT '' AFTER sample_frame,
    ADD COLUMN target_sample_size INT UNSIGNED NULL AFTER sample_method,
    ADD COLUMN quota_policy TEXT NULL AFTER target_sample_size,
    ADD COLUMN response_rate_basis TEXT NULL AFTER quota_policy,
    ADD COLUMN analysis_plan TEXT NULL AFTER response_rate_basis,
    ADD COLUMN weighting_policy TEXT NULL AFTER analysis_plan,
    ADD COLUMN margin_error_note TEXT NULL AFTER weighting_policy,
    ADD COLUMN methodology_disclosure TEXT NULL AFTER margin_error_note,
    ADD COLUMN ethics_note TEXT NULL AFTER methodology_disclosure,
    ADD COLUMN sensitive_data_policy TEXT NULL AFTER ethics_note,
    ADD COLUMN recontact_policy TEXT NULL AFTER sensitive_data_policy,
    ADD COLUMN withdrawal_policy TEXT NULL AFTER recontact_policy,
    ADD COLUMN vendor_name VARCHAR(190) NOT NULL DEFAULT '' AFTER withdrawal_policy,
    ADD COLUMN external_channel_policy TEXT NULL AFTER vendor_name,
    ADD COLUMN invite_token_policy TEXT NULL AFTER external_channel_policy,
    ADD COLUMN qa_status VARCHAR(30) NOT NULL DEFAULT 'unchecked' AFTER invite_token_policy,
    ADD COLUMN qa_note TEXT NULL AFTER qa_status,
    ADD COLUMN questionnaire_version INT UNSIGNED NOT NULL DEFAULT 1 AFTER qa_note,
    ADD COLUMN revision_locked TINYINT(1) NOT NULL DEFAULT 0 AFTER questionnaire_version,
    ADD COLUMN member_group_keys_json LONGTEXT NULL AFTER response_limit_period_seconds,
    ADD KEY idx_sr_survey_forms_qa (qa_status, revision_locked);
