CREATE TABLE IF NOT EXISTS sr_content_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_key VARCHAR(60) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_groups_group_key (group_key),
    KEY idx_sr_content_groups_status_sort (status, sort_order, id)
);

CREATE TABLE IF NOT EXISTS sr_content_storage_cleanup_failures (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_type VARCHAR(60) NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
    storage_key VARCHAR(512) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    attempt_count INT NOT NULL DEFAULT 1,
    last_error TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_storage_cleanup_status (status, updated_at),
    KEY idx_sr_content_storage_cleanup_source (source_type, source_id),
    KEY idx_sr_content_storage_cleanup_storage (storage_driver, storage_key(191))
);

CREATE TABLE IF NOT EXISTS sr_content_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_group_id BIGINT UNSIGNED NULL,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(160) NOT NULL,
    summary TEXT NULL,
    cover_image_url VARCHAR(255) NOT NULL DEFAULT '',
    body_text MEDIUMTEXT NOT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    editor_key VARCHAR(40) NOT NULL DEFAULT 'inherit',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    layout_key VARCHAR(80) NOT NULL DEFAULT '',
    asset_access_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT '',
    asset_access_amount BIGINT NOT NULL DEFAULT 0,
    asset_access_settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_access_amounts_json TEXT NULL,
    asset_access_group_policies_json TEXT NULL,
    asset_access_policy_set_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_action_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_action_module VARCHAR(20) NOT NULL DEFAULT '',
    asset_action_amount BIGINT NOT NULL DEFAULT 0,
    asset_action_settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_action_amounts_json TEXT NULL,
    asset_action_group_policies_json TEXT NULL,
    asset_action_policy_set_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    asset_action_direction VARCHAR(20) NOT NULL DEFAULT 'grant',
    asset_action_label VARCHAR(80) NOT NULL DEFAULT '완료',
    banner_before_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    banner_after_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    popup_layer_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reaction_preset_key VARCHAR(80) NOT NULL DEFAULT '',
    reaction_comment_preset_key VARCHAR(80) NOT NULL DEFAULT '',
    seo_title VARCHAR(160) NOT NULL DEFAULT '',
    seo_description VARCHAR(255) NOT NULL DEFAULT '',
    view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_items_group_status (content_group_id, status, updated_at),
    UNIQUE KEY uq_sr_content_items_slug (slug),
    KEY idx_sr_content_items_status_slug (status, slug),
    KEY idx_sr_content_items_status_updated (status, updated_at),
    KEY idx_sr_content_items_view_count (view_count, id),
    KEY idx_sr_content_items_asset_access (asset_access_enabled, asset_module),
    KEY idx_sr_content_items_asset_action (asset_action_enabled, asset_action_module),
    KEY idx_sr_content_items_created_by (created_by, id),
    KEY idx_sr_content_items_updated_by (updated_by, id)
);

CREATE TABLE IF NOT EXISTS sr_content_revisions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    content_group_id BIGINT UNSIGNED NULL,
    title VARCHAR(160) NOT NULL,
    summary TEXT NULL,
    cover_image_url VARCHAR(255) NOT NULL DEFAULT '',
    body_text MEDIUMTEXT NOT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    editor_key VARCHAR(40) NOT NULL DEFAULT 'inherit',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    layout_key VARCHAR(80) NOT NULL DEFAULT '',
    asset_access_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT '',
    asset_access_amount BIGINT NOT NULL DEFAULT 0,
    asset_access_settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_access_amounts_json TEXT NULL,
    asset_access_group_policies_json TEXT NULL,
    asset_access_policy_set_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_action_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_action_module VARCHAR(20) NOT NULL DEFAULT '',
    asset_action_amount BIGINT NOT NULL DEFAULT 0,
    asset_action_settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_action_amounts_json TEXT NULL,
    asset_action_group_policies_json TEXT NULL,
    asset_action_policy_set_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    asset_action_direction VARCHAR(20) NOT NULL DEFAULT 'grant',
    asset_action_label VARCHAR(80) NOT NULL DEFAULT '완료',
    banner_before_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    banner_after_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    popup_layer_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_revisions_content_id (content_id, id),
    KEY idx_sr_content_revisions_created_by (created_by, id)
);

CREATE TABLE IF NOT EXISTS sr_content_submissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NULL,
    content_group_id BIGINT UNSIGNED NULL,
    author_account_id BIGINT UNSIGNED NOT NULL,
    slug VARCHAR(120) NOT NULL DEFAULT '',
    title VARCHAR(160) NOT NULL,
    summary TEXT NULL,
    body_text MEDIUMTEXT NOT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    review_status VARCHAR(30) NOT NULL DEFAULT 'member_draft',
    publish_target_status VARCHAR(30) NOT NULL DEFAULT 'published',
    review_note TEXT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_submissions_author_status (author_account_id, review_status, updated_at),
    KEY idx_sr_content_submissions_status_updated (review_status, updated_at),
    KEY idx_sr_content_submissions_content (content_id, id),
    KEY idx_sr_content_submissions_group (content_group_id, review_status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_content_author_permissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'allowed',
    review_required_override VARCHAR(20) NOT NULL DEFAULT 'inherit',
    note TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_author_permissions_account (account_id),
    KEY idx_sr_content_author_permissions_status (status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_content_author_applications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NULL,
    application_note TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    review_note TEXT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_author_applications_account (account_id),
    KEY idx_sr_content_author_applications_status (status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_content_author_reward_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    submission_id BIGINT UNSIGNED NOT NULL,
    content_id BIGINT UNSIGNED NOT NULL,
    author_account_id BIGINT UNSIGNED NOT NULL,
    asset_module VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    transaction_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    failure_reason TEXT NULL,
    dedupe_key VARCHAR(191) NOT NULL,
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_author_reward_dedupe (dedupe_key),
    KEY idx_sr_content_author_reward_author (author_account_id, created_at),
    KEY idx_sr_content_author_reward_submission (submission_id),
    KEY idx_sr_content_author_reward_content (content_id),
    KEY idx_sr_content_author_reward_status (status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_content_group_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(120) NOT NULL,
    setting_value TEXT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'string',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_group_settings_key (group_id, setting_key),
    KEY idx_sr_content_group_settings_group (group_id)
);

CREATE TABLE IF NOT EXISTS sr_content_setting_sources (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    setting_key VARCHAR(120) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'content',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_setting_sources_key (content_id, setting_key),
    KEY idx_sr_content_setting_sources_content (content_id)
);

CREATE TABLE IF NOT EXISTS sr_content_asset_policy_sets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    set_key VARCHAR(60) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    policies_json TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_asset_policy_sets_key (set_key),
    KEY idx_sr_content_asset_policy_sets_status (status, title)
);

CREATE TABLE IF NOT EXISTS sr_content_series (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    series_key VARCHAR(60) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    visibility VARCHAR(30) NOT NULL DEFAULT 'public',
    sort_order INT NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_series_key (series_key),
    KEY idx_sr_content_series_status_sort (status, sort_order, id)
);

CREATE TABLE IF NOT EXISTS sr_content_series_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    series_id BIGINT UNSIGNED NOT NULL,
    content_id BIGINT UNSIGNED NOT NULL,
    active_content_id BIGINT UNSIGNED NULL,
    episode_label VARCHAR(120) NOT NULL DEFAULT '',
    item_status VARCHAR(30) NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_series_items_series_content (series_id, content_id),
    UNIQUE KEY uq_sr_content_series_items_active_content (active_content_id),
    KEY idx_sr_content_series_items_series_sort (series_id, item_status, sort_order, id)
);

CREATE TABLE IF NOT EXISTS sr_content_comments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    parent_comment_id BIGINT UNSIGNED NULL,
    thread_root_id BIGINT UNSIGNED NULL,
    depth TINYINT UNSIGNED NOT NULL DEFAULT 1,
    author_account_id BIGINT UNSIGNED NOT NULL,
    author_public_name_snapshot VARCHAR(120) NOT NULL DEFAULT '',
    body_text TEXT NOT NULL,
    is_secret TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'published',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_comments_content_status_id (content_id, status, id),
    KEY idx_sr_content_comments_thread (content_id, status, thread_root_id, parent_comment_id, id),
    KEY idx_sr_content_comments_parent (parent_comment_id),
    KEY idx_sr_content_comments_author_id (author_account_id, id)
);

CREATE TABLE IF NOT EXISTS sr_content_asset_access_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    asset_module VARCHAR(20) NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reference_type VARCHAR(60) NOT NULL,
    reference_id VARCHAR(120) NOT NULL,
    access_kind VARCHAR(40) NOT NULL DEFAULT 'view',
    charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    amount BIGINT NOT NULL,
    settlement_amount BIGINT NOT NULL DEFAULT 0,
    settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    purchase_power_snapshot_json TEXT NULL,
    settlement_kind VARCHAR(30) NOT NULL DEFAULT 'legacy_unknown',
    snapshot_schema_version VARCHAR(40) NOT NULL DEFAULT 'asset_settlement_snapshot_v1',
    rounding_policy_version VARCHAR(40) NOT NULL DEFAULT 'asset_settlement_rounding_v1',
    log_status VARCHAR(20) NOT NULL DEFAULT 'completed',
    group_policy_snapshot_json TEXT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_asset_access_dedupe (dedupe_key),
    KEY idx_sr_content_asset_access_account (account_id, created_at),
    KEY idx_sr_content_asset_access_content (content_id, account_id),
    KEY idx_sr_content_asset_access_transaction (asset_module, transaction_id)
);

CREATE TABLE IF NOT EXISTS sr_content_view_payment_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    content_title_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    content_slug_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    account_id BIGINT UNSIGNED NULL,
    payment_type VARCHAR(40) NOT NULL DEFAULT 'asset_only',
    settlement_kind VARCHAR(30) NOT NULL DEFAULT 'paid',
    charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_module VARCHAR(60) NOT NULL DEFAULT '',
    payable_amount BIGINT NOT NULL DEFAULT 0,
    settlement_amount BIGINT NOT NULL DEFAULT 0,
    settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_access_log_ids_json TEXT NULL,
    coupon_redemption_id BIGINT UNSIGNED NULL,
    coupon_dedupe_key VARCHAR(160) NOT NULL DEFAULT '',
    payment_dedupe_key VARCHAR(190) NOT NULL,
    refund_status VARCHAR(20) NOT NULL DEFAULT '',
    refund_transaction_ids_json TEXT NULL,
    refund_note VARCHAR(255) NOT NULL DEFAULT '',
    refunded_by_account_id BIGINT UNSIGNED NULL,
    refunded_at DATETIME NULL,
    access_revoked_at DATETIME NULL,
    refund_policy_version VARCHAR(40) NOT NULL DEFAULT 'content_view_refund_v1',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_view_payments_dedupe (payment_dedupe_key),
    KEY idx_sr_content_view_payments_content (content_id, created_at),
    KEY idx_sr_content_view_payments_account (account_id, created_at),
    KEY idx_sr_content_view_payments_type (payment_type, created_at),
    KEY idx_sr_content_view_payments_coupon (coupon_redemption_id),
    KEY idx_sr_content_view_payments_refund (refund_status, refunded_at)
);

CREATE TABLE IF NOT EXISTS sr_content_access_entitlements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NULL,
    content_id BIGINT UNSIGNED NOT NULL,
    subject_type VARCHAR(40) NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    access_kind VARCHAR(40) NOT NULL DEFAULT 'view',
    source_kind VARCHAR(30) NOT NULL DEFAULT 'asset',
    source_asset_module VARCHAR(20) NOT NULL DEFAULT '',
    source_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    source_reference VARCHAR(160) NOT NULL DEFAULT '',
    granted_at DATETIME NOT NULL,
    anonymized_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_access_entitlements_account_subject (account_id, subject_type, subject_id, access_kind),
    KEY idx_sr_content_access_entitlements_content (content_id, subject_type, subject_id),
    KEY idx_sr_content_access_entitlements_account (account_id, granted_at),
    KEY idx_sr_content_access_entitlements_anonymized (anonymized_at)
);

CREATE TABLE IF NOT EXISTS sr_content_files (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    title VARCHAR(160) NOT NULL,
    original_name VARCHAR(120) NOT NULL,
    stored_name VARCHAR(120) NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
    storage_key VARCHAR(255) NOT NULL DEFAULT '',
    mime_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    asset_download_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT '',
    asset_download_amount BIGINT NOT NULL DEFAULT 0,
    asset_download_settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    asset_download_amounts_json TEXT NULL,
    asset_download_group_policies_json TEXT NULL,
    asset_download_policy_set_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_files_content_status (content_id, status, id),
    KEY idx_sr_content_files_asset_download (asset_download_enabled, asset_module),
    KEY idx_sr_content_files_storage (storage_driver, storage_key),
    KEY idx_sr_content_files_checksum (checksum_sha256)
);

CREATE TABLE IF NOT EXISTS sr_content_file_links (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    file_id BIGINT UNSIGNED NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_file_links_content_file (content_id, file_id),
    KEY idx_sr_content_file_links_file_status (file_id, status),
    KEY idx_sr_content_file_links_content_status (content_id, status, sort_order, id)
);

CREATE TABLE IF NOT EXISTS sr_content_file_download_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    content_title_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    content_slug_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    file_id BIGINT UNSIGNED NOT NULL,
    file_title_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    file_original_name_snapshot VARCHAR(160) NOT NULL DEFAULT '',
    account_id BIGINT UNSIGNED NULL,
    download_type VARCHAR(20) NOT NULL DEFAULT 'free',
    charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_module VARCHAR(60) NOT NULL DEFAULT '',
    amount BIGINT NOT NULL DEFAULT 0,
    asset_access_log_ids_json TEXT NULL,
    coupon_redemption_id BIGINT UNSIGNED NULL,
    coupon_dedupe_key VARCHAR(160) NOT NULL DEFAULT '',
    refund_status VARCHAR(20) NOT NULL DEFAULT '',
    refund_transaction_ids_json TEXT NULL,
    refund_note VARCHAR(255) NOT NULL DEFAULT '',
    refunded_by_account_id BIGINT UNSIGNED NULL,
    refunded_at DATETIME NULL,
    access_revoked_at DATETIME NULL,
    refund_policy_version VARCHAR(40) NOT NULL DEFAULT 'content_file_download_refund_v1',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_content_file_downloads_content (content_id, created_at),
    KEY idx_sr_content_file_downloads_file (file_id, created_at),
    KEY idx_sr_content_file_downloads_account (account_id, created_at),
    KEY idx_sr_content_file_downloads_type (download_type, created_at),
    KEY idx_sr_content_file_downloads_coupon (coupon_redemption_id),
    KEY idx_sr_content_file_downloads_refund (refund_status, refunded_at)
);

CREATE TABLE IF NOT EXISTS sr_content_asset_action_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    asset_module VARCHAR(20) NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reference_type VARCHAR(60) NOT NULL,
    reference_id VARCHAR(120) NOT NULL,
    action_key VARCHAR(40) NOT NULL DEFAULT 'complete',
    direction VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    settlement_amount BIGINT NOT NULL DEFAULT 0,
    settlement_currency CHAR(3) NOT NULL DEFAULT 'KRW',
    purchase_power_snapshot_json TEXT NULL,
    settlement_kind VARCHAR(30) NOT NULL DEFAULT 'legacy_unknown',
    snapshot_schema_version VARCHAR(40) NOT NULL DEFAULT 'asset_settlement_snapshot_v1',
    rounding_policy_version VARCHAR(40) NOT NULL DEFAULT 'asset_settlement_rounding_v1',
    log_status VARCHAR(20) NOT NULL DEFAULT 'completed',
    group_policy_snapshot_json TEXT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_content_asset_action_dedupe (dedupe_key),
    KEY idx_sr_content_asset_action_account (account_id, created_at),
    KEY idx_sr_content_asset_action_content (content_id, account_id),
    KEY idx_sr_content_asset_action_transaction (asset_module, transaction_id)
);
