<?php

return [
    'content.basic' => [
        'label' => sr_t('content::layout.basic.label'),
        'provider_module_key' => 'content',
        'provider_label' => sr_t('content::layout.provider'),
        'supports' => [
            'site',
            'content',
            'content.home',
            'content.group',
            'content.view',
            'content.form',
            'content.search',
            'community',
            'community.home',
            'community.group',
            'community.list',
            'community.post',
            'community.form',
            'community.search',
            'quiz',
            'quiz.home',
            'quiz.list',
            'quiz.view',
            'quiz.result',
            'survey',
            'survey.home',
            'survey.list',
            'survey.view',
            'survey.complete',
        ],
        'style_profile' => 'minimal',
        'views' => [
            'layout' => SR_ROOT . '/modules/content/theme/basic/layout.php',
            'ui_kit' => SR_ROOT . '/modules/content/theme/basic/ui-kit.php',
        ],
    ],
];
