<?php

return [
    'name' => '콘텐츠',
    'version' => '2026.07.008',
    'type' => 'module',
    'description' => '콘텐츠 작성과 공개 URL을 관리하는 모듈입니다.',
    'admin' => [
        'category' => 'service',
        'category_label' => '서비스',
        'category_order' => 30,
        'menu_order' => 5,
        'icon' => ['type' => 'symbol', 'name' => 'content'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.1',
        'tested_with' => ['0.2.1'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin', 'payment_ledger'],
    ],
    'settings' => [
        'editor' => 'textarea',
        'editor_toolbar_preset' => 'standard',
        'comment_editor' => 'textarea',
        'external_embed_enabled' => true,
        'internal_embed_enabled' => true,
        'plain_text_auto_link_urls' => false,
        'plain_text_auto_link_new_tab' => false,
        'secret_comments_enabled' => false,
        'comment_extra_fields_json' => '[]',
        'reaction_enabled' => true,
        'reaction_preset_key' => '',
        'reaction_comment_preset_key' => '',
        'once_history_policy' => 'all_access',
        'layout_key' => 'content.basic',
        'theme_key' => 'basic',
        'layout_primary_menu_key' => 'header',
        'layout_extra_menu_keys_json' => [],
        'sidebar_enabled' => true,
        'sidebar_menu_type' => 'groups',
        'sidebar_site_menu_key' => '',
        'sidebar_popular_limit' => 5,
        'sidebar_comments_limit' => 5,
        'business_info_visible' => true,
        'series_enabled' => true,
        'member_submission_enabled' => false,
        'identity_content_view_required' => false,
        'identity_content_view_adult_required' => false,
        'identity_author_application_required' => false,
        'identity_author_application_adult_required' => false,
        'member_submission_default_review_required' => false,
        'member_submission_author_reward_enabled' => false,
        'member_submission_author_reward_asset_module' => '',
        'member_submission_author_reward_amount' => 0,
        'multi_asset_payment_enabled' => true,
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'retention-targets.php',
            'operational-status.php',
            'extension-points.php',
            'menu-links.php',
            'privacy-export.php',
            'privacy-cleanup.php',
            'sitemap.php',
            'dashboard.php',
            'homepage-candidates.php',
            'member-group-rules.php',
            'coupon-targets.php',
            'banner-references.php',
            'popup-layer-references.php',
            'member-group-references.php',
            'member-only-routes.php',
            'layout-options.php',
            'url-embed-targets.php',
            'reaction-targets.php',
            'payment-ledger-targets.php',
        ],
        'consumes' => [
            'site-menu-provider.php',
            'member-assets.php',
            'notification-events.php',
            'admin-notification-events.php',
        ],
    ],
    'service_domain' => [
        'main_page' => [
            'label' => '콘텐츠',
            'menu_label' => 'Contents',
            'path' => '/content',
        ],
    ],
];
