<?php

return [
    'name' => '콘텐츠',
    'version' => '2026.06.016',
    'type' => 'module',
    'description' => '콘텐츠 작성과 공개 URL을 관리하는 모듈입니다.',
    'admin' => [
        'category' => 'service',
        'category_label' => '서비스',
        'category_order' => 30,
        'menu_order' => 5,
        'icon' => ['type' => 'symbol', 'name' => 'content'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin'],
    ],
    'settings' => [
        'editor' => 'textarea',
        'editor_toolbar_preset' => 'content_basic',
        'plain_text_auto_link_urls' => false,
        'once_history_policy' => 'all_access',
        'layout_key' => 'content.basic',
        'layout_primary_menu_key' => 'header',
        'layout_secondary_menu_key' => '',
        'layout_tertiary_menu_key' => '',
        'layout_quaternary_menu_key' => '',
        'layout_quinary_menu_key' => '',
        'member_submission_enabled' => false,
        'member_submission_default_review_required' => true,
        'member_submission_author_reward_enabled' => false,
        'member_submission_author_reward_asset_module' => '',
        'member_submission_author_reward_amount' => 0,
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'extension-points.php',
            'menu-links.php',
            'privacy-export.php',
            'privacy-cleanup.php',
            'sitemap.php',
            'homepage-candidates.php',
            'member-group-rules.php',
            'coupon-targets.php',
            'banner-references.php',
            'popup-layer-references.php',
            'member-group-references.php',
            'layout-options.php',
            'embed-manager-targets.php',
        ],
        'consumes' => [
            'member-assets.php',
            'notification-events.php',
            'admin-notification-events.php',
        ],
    ],
    'service_domain' => [
        'main_page' => [
            'label' => '콘텐츠 메인',
            'path' => '/content',
        ],
    ],
];
