<?php

return [
    'GET /content' => 'actions/home.php',
    'GET /content/download' => 'actions/download.php',
    'POST /content/download' => 'actions/download.php',
    'GET /content/cover-image' => 'actions/cover-image.php',
    'GET /content/body-file' => 'actions/body-file.php',
    'GET /content/group' => 'actions/group.php',
    'POST /content/action' => 'actions/action.php',
    'POST /content/comment' => 'actions/comment.php',
    'POST /content/*' => 'actions/view.php',
    'GET /content/*' => 'actions/view.php',
    'GET /admin/content' => 'actions/admin-contents.php',
    'GET /admin/content/series' => 'actions/admin-series.php',
    'POST /admin/content/series' => 'actions/admin-series.php',
    'GET /admin/content/settings' => 'actions/admin-settings.php',
    'POST /admin/content/settings' => 'actions/admin-settings.php',
    'GET /admin/content/files' => 'actions/admin-download-files.php',
    'POST /admin/content/files' => 'actions/admin-download-files.php',
    'GET /admin/content/link-card-targets' => 'actions/admin-link-card-targets.php',
    'POST /admin/content/body-files/upload' => 'actions/admin-body-file-upload.php',
    'GET /admin/content/file-downloads' => 'actions/admin-file-downloads.php',
    'POST /admin/content/file-downloads' => 'actions/admin-file-downloads.php',
    'GET /admin/content/asset-policy-sets' => 'actions/admin-asset-policy-sets.php',
    'POST /admin/content/asset-policy-sets' => 'actions/admin-asset-policy-sets.php',
    'GET /admin/content/new' => 'actions/admin-content-new.php',
    'GET /admin/content/edit' => 'actions/admin-content-edit.php',
    'POST /admin/content/copy' => 'actions/admin-content-copy.php',
    'POST /admin/content/save' => 'actions/admin-content-save.php',
    'POST /admin/content/delete' => 'actions/admin-content-delete.php',
    'GET /admin/content-groups' => 'actions/admin-content-groups.php',
    'POST /admin/content-groups' => 'actions/admin-content-groups.php',
    'GET /admin/content-groups/new' => 'actions/admin-content-group-new.php',
    'GET /admin/content-groups/edit' => 'actions/admin-content-group-edit.php',
];
