CREATE TABLE IF NOT EXISTS sr_identity_verification_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    verification_key VARCHAR(80) NOT NULL,
    provider_key VARCHAR(60) NOT NULL,
    method VARCHAR(60) NOT NULL DEFAULT '',
    account_id BIGINT UNSIGNED NULL,
    purpose VARCHAR(80) NOT NULL,
    subject_module VARCHAR(60) NOT NULL DEFAULT '',
    subject_type VARCHAR(60) NOT NULL DEFAULT '',
    subject_id VARCHAR(120) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    state_token_hash CHAR(64) NOT NULL,
    nonce_hash CHAR(64) NOT NULL DEFAULT '',
    provider_transaction_id VARCHAR(120) NOT NULL DEFAULT '',
    provider_reference VARCHAR(255) NOT NULL DEFAULT '',
    return_url VARCHAR(500) NOT NULL DEFAULT '',
    confirm_path VARCHAR(255) NOT NULL DEFAULT '',
    requested_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    failed_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    failure_code VARCHAR(80) NOT NULL DEFAULT '',
    failure_message VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_identity_attempt_key (verification_key),
    UNIQUE KEY uq_sr_identity_attempt_state_hash (state_token_hash),
    KEY idx_sr_identity_attempt_account_purpose (account_id, purpose, status, expires_at),
    KEY idx_sr_identity_attempt_provider_reference (provider_key, provider_reference),
    KEY idx_sr_identity_attempt_status (status, expires_at)
);

CREATE TABLE IF NOT EXISTS sr_identity_verification_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    provider_key VARCHAR(60) NOT NULL,
    provider_transaction_id VARCHAR(120) NOT NULL DEFAULT '',
    ci_hash CHAR(64) NOT NULL DEFAULT '',
    di_hash CHAR(64) NOT NULL DEFAULT '',
    name_hash CHAR(64) NOT NULL DEFAULT '',
    phone_hash CHAR(64) NOT NULL DEFAULT '',
    birth_date DATE NULL,
    gender VARCHAR(20) NOT NULL DEFAULT '',
    nationality VARCHAR(20) NOT NULL DEFAULT '',
    age_over_14 TINYINT(1) NULL,
    age_over_19 TINYINT(1) NULL,
    result_summary_json TEXT NULL,
    verified_at DATETIME NOT NULL,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_identity_result_attempt (attempt_id),
    KEY idx_sr_identity_result_account (account_id, verified_at),
    KEY idx_sr_identity_result_ci (ci_hash)
);

CREATE TABLE IF NOT EXISTS sr_identity_verification_links (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id BIGINT UNSIGNED NOT NULL,
    result_id BIGINT UNSIGNED NOT NULL,
    purpose VARCHAR(80) NOT NULL,
    linked_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_identity_link_result_purpose (result_id, purpose),
    KEY idx_sr_identity_link_account_purpose (account_id, purpose, revoked_at, linked_at)
);

CREATE TABLE IF NOT EXISTS sr_identity_verification_identity_locks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ci_hash CHAR(64) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    result_id BIGINT UNSIGNED NOT NULL,
    first_linked_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_identity_lock_ci_hash (ci_hash),
    KEY idx_sr_identity_lock_account (account_id, updated_at)
);
