<?php

return [
    'GET /admin' => 'actions/dashboard.php',
    'GET /admin/settings' => 'actions/settings.php',
    'POST /admin/settings' => 'actions/settings.php',
    'GET /admin/icon-image' => 'actions/icon-image.php',
    'POST /admin/color-scheme' => 'actions/color-scheme.php',
    'GET /admin/homepage' => 'actions/homepage.php',
    'POST /admin/homepage' => 'actions/homepage.php',
    'GET /admin/menu' => 'actions/menu.php',
    'POST /admin/menu' => 'actions/menu.php',
    'GET /admin/modules' => 'actions/modules.php',
    'POST /admin/modules' => 'actions/modules.php',
    'GET /admin/updates' => 'actions/updates.php',
    'POST /admin/updates' => 'actions/updates.php',
    'GET /admin/operations' => 'actions/operations.php',
    'GET /admin/storage-cache' => 'actions/storage-cache.php',
    'POST /admin/storage-cache' => 'actions/storage-cache.php',
    'GET /admin/roles' => 'actions/roles.php',
    'POST /admin/roles' => 'actions/roles.php',
    'GET /admin/audit-logs' => 'actions/audit-logs.php',
    'GET /admin/ui-kit' => 'actions/ui-kit.php',
    'GET /admin/retention' => 'actions/retention.php',
    'POST /admin/retention' => 'actions/retention.php',
];
