<?php

return [
    'name' => '커뮤니티',
    'version' => '2026.06.035',
    'type' => 'module',
    'description' => '게시판형 커뮤니티 모듈입니다.',
    'admin' => [
        'category' => 'service',
        'category_label' => '서비스',
        'category_order' => 30,
        'menu_order' => 10,
        'icon' => ['type' => 'symbol', 'name' => 'message-circle'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin'],
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'menu-links.php',
            'extension-points.php',
            'privacy-export.php',
            'privacy-cleanup.php',
            'sitemap.php',
            'member-group-rules.php',
            'dashboard.php',
            'layout-options.php',
            'coupon-targets.php',
            'banner-references.php',
            'popup-layer-references.php',
            'member-group-references.php',
            'member-only-routes.php',
            'embed-manager-targets.php',
            'embed-manager-url-targets.php',
            'reaction-targets.php',
            'antispam-targets.php',
        ],
        'consumes' => [
            'member-assets.php',
            'notification-events.php',
            'admin-notification-events.php',
        ],
    ],
    'service_domain' => [
        'main_page' => [
            'label' => '커뮤니티',
            'path' => '/community',
        ],
    ],
    'settings' => [
        'posts_per_page' => 20,
        'comments_per_page' => 50,
        'post_create_window_seconds' => 300,
        'post_create_limit' => 10,
        'comment_create_window_seconds' => 300,
        'comment_create_limit' => 30,
        'report_create_window_seconds' => 300,
        'report_create_limit' => 20,
        'message_create_window_seconds' => 300,
        'message_create_limit' => 20,
        'attachment_max_bytes' => 2097152,
        'image_uploads_enabled' => true,
        'thumbnail_enabled' => true,
        'thumbnail_criterion' => 'width',
        'thumbnail_min_width' => 320,
        'thumbnail_min_bytes' => 102400,
        'file_uploads_enabled' => false,
        'file_attachment_max_bytes' => 5242880,
        'file_attachment_max_count' => 3,
        'file_allowed_extensions' => ['pdf', 'txt', 'csv', 'zip', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'hwp'],
        'level_enabled' => false,
        'level_display_name' => '레벨',
        'level_short_label' => 'Lv.',
        'level_max_value' => 10,
        'level_auto_recalculate' => false,
        'level_post_score' => 10,
        'level_comment_score' => 2,
        'message_write_policy' => 'member',
        'message_write_group_keys' => [],
        'message_write_min_level' => 0,
        'layout_key' => 'community.basic',
        'layout_primary_menu_key' => 'header',
        'layout_secondary_menu_key' => '',
        'layout_tertiary_menu_key' => '',
        'layout_quaternary_menu_key' => '',
        'layout_quinary_menu_key' => '',
        'post_editor' => 'textarea',
        'post_toolbar_preset' => 'community_post_basic',
        'embed_enabled' => true,
        'plain_text_auto_link_urls' => false,
        'secret_posts_enabled' => false,
        'secret_comments_enabled' => false,
        'privacy_consent_enabled' => false,
        'privacy_consent_document_key' => 'community_privacy_default',
        'privacy_consent_post_document_key' => '',
        'privacy_consent_comment_document_key' => '',
        'privacy_consent_attachment_upload_document_key' => '',
        'privacy_consent_document_inherit_policy' => 'override',
        'privacy_consent_title' => '개인정보 수집 및 이용동의',
        'privacy_consent_body' => '',
        'privacy_consent_version' => '1',
        'privacy_consent_require_post' => false,
        'privacy_consent_require_comment' => false,
        'privacy_consent_require_attachment_upload' => false,
        'reaction_enabled' => true,
        'reaction_post_preset_key' => '',
        'reaction_comment_preset_key' => '',
        'post_reward_enabled' => false,
        'post_reward_asset_module' => '',
        'post_reward_amount' => 0,
        'post_reward_group_policies_json' => '',
        'post_reward_policy_set_id' => 0,
        'post_reward_reversal_enabled' => false,
        'comment_reward_enabled' => false,
        'comment_reward_asset_module' => '',
        'comment_reward_amount' => 0,
        'comment_reward_group_policies_json' => '',
        'comment_reward_policy_set_id' => 0,
        'comment_reward_reversal_enabled' => false,
        'write_charge_enabled' => false,
        'write_charge_asset_module' => '',
        'write_charge_amount' => 0,
        'write_charge_settlement_currency' => 'KRW',
        'write_charge_amounts_json' => '',
        'write_charge_group_policies_json' => '',
        'write_charge_policy_set_id' => 0,
        'message_charge_enabled' => false,
        'message_charge_asset_module' => '',
        'message_charge_amount' => 0,
        'message_charge_settlement_currency' => 'KRW',
        'message_charge_amounts_json' => '',
        'message_charge_group_policies_json' => '',
        'message_charge_policy_set_id' => 0,
        'comment_charge_enabled' => false,
        'comment_charge_asset_module' => '',
        'comment_charge_amount' => 0,
        'comment_charge_settlement_currency' => 'KRW',
        'comment_charge_amounts_json' => '',
        'comment_charge_group_policies_json' => '',
        'comment_charge_policy_set_id' => 0,
        'paid_read_enabled' => false,
        'paid_read_asset_module' => '',
        'paid_read_amount' => 0,
        'paid_read_settlement_currency' => 'KRW',
        'paid_read_amounts_json' => '',
        'paid_read_group_policies_json' => '',
        'paid_read_policy_set_id' => 0,
        'paid_read_charge_policy' => 'once',
        'once_history_policy' => 'all_access',
        'paid_attachment_download_enabled' => false,
        'paid_attachment_download_asset_module' => '',
        'paid_attachment_download_amount' => 0,
        'paid_attachment_download_settlement_currency' => 'KRW',
        'paid_attachment_download_amounts_json' => '',
        'paid_attachment_download_group_policies_json' => '',
        'paid_attachment_download_policy_set_id' => 0,
        'paid_attachment_download_charge_policy' => 'once',
        'paid_attachment_download_publisher_reward_enabled' => false,
        'paid_attachment_download_publisher_reward_rate' => 0,
    ],
];
