CREATE TABLE IF NOT EXISTS sr_quiz_sets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_key VARCHAR(64) NOT NULL,
    title VARCHAR(190) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    quiz_mode VARCHAR(30) NOT NULL DEFAULT 'scored',
    scoring_model VARCHAR(40) NOT NULL DEFAULT 'correct_answer',
    pass_score INT NULL,
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    time_limit_seconds INT UNSIGNED NULL,
    attempt_limit_policy VARCHAR(30) NOT NULL DEFAULT 'unlimited',
    attempt_limit_period_seconds INT UNSIGNED NULL,
    member_group_keys_json LONGTEXT NULL,
    comments_enabled TINYINT(1) NOT NULL DEFAULT 0,
    secret_comments_enabled TINYINT(1) NOT NULL DEFAULT 0,
    reward_enabled TINYINT(1) NOT NULL DEFAULT 0,
    reward_scope VARCHAR(20) NOT NULL DEFAULT 'per_quiz',
    created_by_account_id BIGINT UNSIGNED NULL,
    updated_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_sets_quiz_key (quiz_key),
    KEY idx_sr_quiz_sets_status (status),
    KEY idx_sr_quiz_sets_status_dates (status, starts_at, ends_at),
    KEY idx_sr_quiz_sets_mode_model (quiz_mode, scoring_model),
    KEY idx_sr_quiz_sets_reward (reward_enabled)
);

CREATE TABLE IF NOT EXISTS sr_quiz_comments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    parent_comment_id BIGINT UNSIGNED NULL,
    thread_root_id BIGINT UNSIGNED NULL,
    depth TINYINT UNSIGNED NOT NULL DEFAULT 1,
    author_account_id BIGINT UNSIGNED NULL,
    author_public_name_snapshot VARCHAR(120) NOT NULL DEFAULT '',
    body_text TEXT NOT NULL,
    is_secret TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'published',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_comments_quiz_status_id (quiz_id, status, id),
    KEY idx_sr_quiz_comments_thread (quiz_id, status, thread_root_id, parent_comment_id, id),
    KEY idx_sr_quiz_comments_parent (parent_comment_id),
    KEY idx_sr_quiz_comments_author_id (author_account_id, id),
    KEY idx_sr_quiz_comments_created (created_at, id)
);

CREATE TABLE IF NOT EXISTS sr_quiz_sources (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    source_module VARCHAR(40) NOT NULL,
    source_type VARCHAR(60) NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    cta_label VARCHAR(120) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_sources_target (quiz_id, source_module, source_type, source_id),
    KEY idx_sr_quiz_sources_source (source_module, source_type, source_id),
    KEY idx_sr_quiz_sources_quiz_status (quiz_id, status, sort_order)
);

CREATE TABLE IF NOT EXISTS sr_quiz_questions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    question_key VARCHAR(64) NOT NULL,
    question_type VARCHAR(30) NOT NULL DEFAULT 'single_choice',
    prompt TEXT NOT NULL,
    help_text TEXT NULL,
    required TINYINT(1) NOT NULL DEFAULT 1,
    score_value INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_questions_key (quiz_id, question_key),
    KEY idx_sr_quiz_questions_sort (quiz_id, sort_order)
);

CREATE TABLE IF NOT EXISTS sr_quiz_choices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    question_id BIGINT UNSIGNED NOT NULL,
    choice_key VARCHAR(64) NOT NULL,
    label VARCHAR(255) NOT NULL,
    description TEXT NULL,
    is_correct TINYINT(1) NOT NULL DEFAULT 0,
    score_value INT NOT NULL DEFAULT 0,
    category_key VARCHAR(64) NULL,
    category_weight INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_choices_key (question_id, choice_key),
    KEY idx_sr_quiz_choices_sort (question_id, sort_order),
    KEY idx_sr_quiz_choices_category (category_key)
);

CREATE TABLE IF NOT EXISTS sr_quiz_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    result_key VARCHAR(64) NOT NULL,
    title VARCHAR(190) NOT NULL,
    summary TEXT NULL,
    body MEDIUMTEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_results_key (quiz_id, result_key),
    KEY idx_sr_quiz_results_status (quiz_id, status, sort_order)
);

CREATE TABLE IF NOT EXISTS sr_quiz_result_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    result_id BIGINT UNSIGNED NOT NULL,
    rule_type VARCHAR(40) NOT NULL,
    min_score INT NULL,
    max_score INT NULL,
    category_key VARCHAR(64) NULL,
    threshold_value INT NULL,
    priority INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_result_rules_quiz (quiz_id, rule_type, priority),
    KEY idx_sr_quiz_result_rules_result (result_id)
);

CREATE TABLE IF NOT EXISTS sr_quiz_reward_policies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    trigger_type VARCHAR(30) NOT NULL DEFAULT 'passed',
    result_id BIGINT UNSIGNED NULL,
    reward_provider VARCHAR(30) NOT NULL DEFAULT 'ledger_asset',
    reward_module VARCHAR(40) NOT NULL,
    reward_code VARCHAR(120) NOT NULL,
    reward_amount INT NULL,
    dedupe_scope VARCHAR(20) NOT NULL DEFAULT 'per_quiz',
    sort_order INT NOT NULL DEFAULT 0,
    settings_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_reward_policies_quiz (quiz_id, status, sort_order),
    KEY idx_sr_quiz_reward_policies_provider (reward_provider, reward_module),
    KEY idx_sr_quiz_reward_policies_scope (dedupe_scope),
    KEY idx_sr_quiz_reward_policies_result (result_id)
);

CREATE TABLE IF NOT EXISTS sr_quiz_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'started',
    source_module VARCHAR(40) NULL,
    source_type VARCHAR(60) NULL,
    source_id BIGINT UNSIGNED NULL,
    source_title_snapshot VARCHAR(255) NULL,
    source_url_snapshot VARCHAR(255) NULL,
    return_url VARCHAR(255) NULL,
    started_at DATETIME NULL,
    submitted_at DATETIME NULL,
    scored_at DATETIME NULL,
    rewarded_at DATETIME NULL,
    expires_at DATETIME NULL,
    canceled_at DATETIME NULL,
    total_score INT NULL,
    passed TINYINT(1) NULL,
    selected_result_id BIGINT UNSIGNED NULL,
    answer_snapshot_json LONGTEXT NULL,
    scoring_snapshot_json LONGTEXT NULL,
    result_snapshot_json LONGTEXT NULL,
    user_agent_hash VARCHAR(128) NULL,
    ip_hash VARCHAR(128) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_attempts_quiz_account (quiz_id, account_id, created_at),
    KEY idx_sr_quiz_attempts_account (account_id, created_at),
    KEY idx_sr_quiz_attempts_source (source_module, source_type, source_id),
    KEY idx_sr_quiz_attempts_status (status, updated_at)
);

CREATE TABLE IF NOT EXISTS sr_quiz_attempt_answers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT UNSIGNED NOT NULL,
    question_id BIGINT UNSIGNED NULL,
    question_key VARCHAR(64) NOT NULL,
    choice_id BIGINT UNSIGNED NULL,
    choice_key VARCHAR(64) NULL,
    answer_text TEXT NULL,
    answer_snapshot_json LONGTEXT NOT NULL,
    score_awarded INT NULL,
    category_scores_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_attempt_answers_attempt (attempt_id),
    KEY idx_sr_quiz_attempt_answers_question (question_id),
    KEY idx_sr_quiz_attempt_answers_choice (choice_id)
);

CREATE TABLE IF NOT EXISTS sr_quiz_attempt_result_scores (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT UNSIGNED NOT NULL,
    result_id BIGINT UNSIGNED NULL,
    category_key VARCHAR(64) NULL,
    score_value INT NOT NULL DEFAULT 0,
    is_selected TINYINT(1) NOT NULL DEFAULT 0,
    snapshot_json LONGTEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_quiz_attempt_result_scores_attempt (attempt_id),
    KEY idx_sr_quiz_attempt_result_scores_selected (attempt_id, is_selected),
    KEY idx_sr_quiz_attempt_result_scores_category (category_key)
);

CREATE TABLE IF NOT EXISTS sr_quiz_reward_grants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quiz_id BIGINT UNSIGNED NOT NULL,
    attempt_id BIGINT UNSIGNED NOT NULL,
    reward_policy_id BIGINT UNSIGNED NULL,
    account_id BIGINT UNSIGNED NULL,
    source_module VARCHAR(40) NULL,
    source_type VARCHAR(60) NULL,
    source_id BIGINT UNSIGNED NULL,
    reward_provider VARCHAR(30) NOT NULL,
    reward_module VARCHAR(40) NOT NULL,
    reward_code VARCHAR(120) NOT NULL,
    reward_amount INT NULL,
    dedupe_scope VARCHAR(20) NOT NULL,
    dedupe_key VARCHAR(190) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    provider_reference_type VARCHAR(60) NULL,
    provider_reference_id VARCHAR(120) NULL,
    request_snapshot_json LONGTEXT NULL,
    result_snapshot_json LONGTEXT NULL,
    error_message TEXT NULL,
    admin_resolution_type VARCHAR(40) NULL,
    resolved_by_account_id BIGINT UNSIGNED NULL,
    resolved_at DATETIME NULL,
    resolution_note TEXT NULL,
    manual_completion_reference VARCHAR(190) NULL,
    replacement_grant_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    granted_at DATETIME NULL,
    failed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_quiz_reward_grants_dedupe (dedupe_key),
    KEY idx_sr_quiz_reward_grants_attempt (attempt_id),
    KEY idx_sr_quiz_reward_grants_account (account_id, created_at),
    KEY idx_sr_quiz_reward_grants_quiz_status (quiz_id, status),
    KEY idx_sr_quiz_reward_grants_provider (reward_provider, reward_module),
    KEY idx_sr_quiz_reward_grants_reference (provider_reference_type, provider_reference_id),
    KEY idx_sr_quiz_reward_grants_policy (reward_policy_id)
);
