<?php

return [
    'name' => '퀴즈·테스트',
    'version' => '2026.07.007',
    'type' => 'module',
    'description' => '퀴즈 응시, 채점, 콘텐츠 연계 보상을 관리하는 모듈입니다.',
    'admin' => [
        'category' => 'service',
        'category_label' => '서비스',
        'category_order' => 30,
        'menu_order' => 11,
        'icon' => ['type' => 'symbol', 'name' => 'quiz'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.1',
        'tested_with' => ['0.2.1'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin', 'content'],
    ],
    'settings' => [
        'layout_key' => 'quiz.basic',
        'theme_key' => 'basic',
        'skin_key' => 'basic',
        'layout_primary_menu_key' => 'header',
        'layout_extra_menu_keys_json' => [],
        'sidebar_enabled' => true,
        'sidebar_menu_type' => 'groups',
        'sidebar_site_menu_key' => '',
        'sidebar_popular_limit' => 5,
        'sidebar_comments_limit' => 5,
        'default_status' => 'draft',
        'default_quiz_mode' => 'scored',
        'default_scoring_model' => 'correct_answer',
        'default_pass_score' => 1,
        'default_question_choice_count' => 4,
        'default_question_score' => 1,
        'default_attempt_limit_policy' => 'unlimited',
        'default_attempt_limit_period_seconds' => '',
        'default_reward_enabled' => true,
        'default_reward_provider' => 'ledger_asset',
        'default_reward_module' => '',
        'default_reward_coupon_definition_id' => '',
        'default_reward_amount' => '',
        'default_reward_dedupe_scope' => 'per_quiz',
        'default_cta_label' => '퀴즈 풀기',
        'internal_embed_enabled' => true,
        'identity_view_required' => false,
        'identity_view_adult_required' => false,
        'business_info_visible' => true,
        'reaction_preset_key' => '',
        'reaction_comment_preset_key' => '',
        'comment_editor' => 'textarea',
        'comment_extra_fields_json' => '[]',
        'public_list_limit' => 50,
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'operational-status.php',
            'menu-links.php',
            'layout-options.php',
            'privacy-export.php',
            'privacy-cleanup.php',
            'dashboard.php',
            'extension-points.php',
            'coupon-references.php',
            'coupon-targets.php',
            'sitemap.php',
            'member-only-routes.php',
            'url-embed-targets.php',
            'reaction-targets.php',
        ],
        'consumes' => [
            'site-menu-provider.php',
            'member-assets.php',
            'notification-events.php',
        ],
    ],
    'service_domain' => [
        'main_page' => [
            'label' => '퀴즈·테스트',
            'menu_label' => 'Quiz',
            'path' => '/quiz',
        ],
    ],
];
