<?php

return [
    'member.email_verification' => [
        'label' => '회원 이메일 인증',
        'description' => '회원가입, 인증 재발송, 로그인 유발 재발송, OAuth 가입 완료에서 공유하는 이메일 인증 메일입니다.',
        'category' => 'transactional_email',
        'owner_module' => 'member',
        'channels' => ['email'],
        'pipeline' => 'config_mail',
        'editable' => true,
        'disable_policy' => 'fallback_to_default',
        'subject_template' => '이메일 인증 안내',
        'body_template' => "아래 링크를 열어 이메일 인증을 완료하세요.\n\n{verification_url}",
        'variables' => [
            'site_name' => '사이트명',
            'verification_url' => '이메일 인증 URL',
            'expires_minutes' => '인증 URL 만료 시간(분)',
        ],
        'required_variables' => ['verification_url'],
        'sensitive_variables' => ['verification_url'],
        'sample_values' => [
            'site_name' => '산란',
            'verification_url' => 'https://example.test/email/verify?token=dummy',
            'expires_minutes' => '30',
        ],
    ],
    'member.password_reset' => [
        'label' => '비밀번호 재설정',
        'description' => '비밀번호 재설정 요청 시 발송하는 메일입니다.',
        'category' => 'transactional_email',
        'owner_module' => 'member',
        'channels' => ['email'],
        'pipeline' => 'config_mail',
        'editable' => true,
        'disable_policy' => 'fallback_to_default',
        'subject_template' => '비밀번호 재설정 안내',
        'body_template' => "아래 링크를 열어 비밀번호를 재설정하세요.\n\n{reset_url}",
        'variables' => [
            'site_name' => '사이트명',
            'reset_url' => '비밀번호 재설정 URL',
            'expires_minutes' => '재설정 URL 만료 시간(분)',
        ],
        'required_variables' => ['reset_url'],
        'sensitive_variables' => ['reset_url'],
        'sample_values' => [
            'site_name' => '산란',
            'reset_url' => 'https://example.test/password/reset/confirm?token=dummy',
            'expires_minutes' => '30',
        ],
    ],
    'member.login_mfa_email_code' => [
        'label' => '로그인 2차 인증 이메일 코드',
        'description' => '로그인 2차 인증에서 이메일 인증 코드를 발송하는 메일입니다.',
        'category' => 'transactional_email',
        'owner_module' => 'member',
        'channels' => ['email'],
        'pipeline' => 'config_mail',
        'editable' => true,
        'disable_policy' => 'fallback_to_default',
        'subject_template' => '로그인 2차 인증 코드',
        'body_template' => "로그인을 계속하려면 아래 인증 코드를 입력하세요.\n\n인증 코드: {mfa_code}\n\n이 코드는 {expires_minutes}분 동안만 사용할 수 있습니다.",
        'variables' => [
            'site_name' => '사이트명',
            'mfa_code' => '이메일 인증 코드',
            'expires_minutes' => '인증 코드 만료 시간(분)',
        ],
        'required_variables' => ['mfa_code', 'expires_minutes'],
        'sensitive_variables' => ['mfa_code'],
        'sample_values' => [
            'site_name' => '산란',
            'mfa_code' => '123456',
            'expires_minutes' => '5',
        ],
    ],
];
