<?php

return [
    'name' => '회원',
    'version' => '2026.07.002',
    'type' => 'module',
    'description' => '회원 계정, 인증, 마이페이지 모듈입니다.',
    'admin' => [
        'category' => 'member',
        'category_label' => '회원',
        'category_order' => 10,
        'menu_order' => 10,
        'icon' => ['type' => 'symbol', 'name' => 'users'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['admin'],
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'retention-targets.php',
            'extension-points.php',
            'menu-links.php',
            'privacy-export.php',
            'dashboard.php',
            'delivery-templates.php',
            'member-group-references.php',
            'antispam-targets.php',
            'member-mfa-providers.php',
        ],
        'consumes' => [
            'notification-events.php',
            'member-group-rules.php',
            'member-registration.php',
            'privacy-cleanup.php',
            'member-withdrawal-assets.php',
            'member-group-references.php',
            'member-mfa-providers.php',
        ],
    ],
    'settings' => [
        'allow_registration' => true,
        'email_verification_enabled' => true,
        'identity_registration_mode' => 'disabled',
        'identity_withdrawal_required' => false,
        'identity_account_security_required' => false,
        'login_identifier' => 'both',
        'mfa_login_mode' => 'disabled',
        'mfa_login_enabled' => false,
        'mfa_login_providers_json' => '["email","totp"]',
        'session_lifetime_seconds' => 86400,
        'login_throttle_window_seconds' => 900,
        'login_throttle_account_limit' => 5,
        'login_throttle_ip_limit' => 20,
        'password_reset_throttle_window_seconds' => 900,
        'password_reset_throttle_account_limit' => 3,
        'password_reset_throttle_ip_limit' => 10,
        'email_verification_throttle_window_seconds' => 900,
        'email_verification_throttle_account_limit' => 3,
        'email_verification_throttle_ip_limit' => 20,
        'register_throttle_window_seconds' => 900,
        'register_throttle_ip_limit' => 10,
        'registration_terms_document_key' => 'member_terms',
        'registration_privacy_document_key' => 'member_privacy_collection',
        'registration_marketing_document_key' => 'member_marketing',
        'member_skin_key' => 'basic',
        'profile_birth_date_enabled' => true,
        'profile_birth_date_required' => false,
        'profile_is_adult_enabled' => true,
        'profile_is_adult_required' => false,
        'profile_image_enabled' => true,
        'profile_image_required' => false,
        'profile_image_size_small' => 24,
        'profile_image_size_medium' => 32,
        'profile_image_size_large' => 40,
        'profile_fields_json' => '[{"key":"phone","label":"휴대폰 번호","type":"text","required":false,"options":[],"visibility":"public","show_on_profile":false,"show_in_admin":true,"privacy_purpose":"회원 본인확인 및 연락처 관리","export_policy":"include","cleanup_policy":"anonymize"}]',
        'profile_field_order_json' => '["extra:phone"]',
        'nickname_enabled' => true,
        'nickname_required' => true,
    ],
];
