<?php

return [
    'name' => '회원',
    'version' => '2026.06.004',
    'type' => 'module',
    'description' => '회원 계정, 인증, 마이페이지 모듈입니다.',
    'admin' => [
        'category' => 'member',
        'category_label' => '회원',
        'category_order' => 10,
        'menu_order' => 10,
        'icon' => ['type' => 'symbol', 'name' => 'users'],
        'stylesheets' => ['assets/admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'retention-targets.php',
            'extension-points.php',
            'menu-links.php',
            'privacy-export.php',
            'dashboard.php',
            'member-group-references.php',
            'antispam-targets.php',
        ],
        'consumes' => [
            'member-group-rules.php',
            'member-registration.php',
            'privacy-cleanup.php',
            'member-withdrawal-assets.php',
            'member-group-references.php',
        ],
    ],
    'settings' => [
        'allow_registration' => true,
        'email_verification_enabled' => true,
        'login_identifier' => 'both',
        'login_throttle_window_seconds' => 900,
        'login_throttle_account_limit' => 5,
        'login_throttle_ip_limit' => 20,
        'password_reset_throttle_window_seconds' => 900,
        'password_reset_throttle_account_limit' => 3,
        'password_reset_throttle_ip_limit' => 10,
        'email_verification_throttle_window_seconds' => 900,
        'email_verification_throttle_account_limit' => 3,
        'email_verification_throttle_ip_limit' => 20,
        'register_throttle_window_seconds' => 900,
        'register_throttle_ip_limit' => 10,
        'registration_terms_document_key' => 'member_terms',
        'registration_privacy_document_key' => 'member_privacy_collection',
        'registration_marketing_document_key' => 'member_marketing',
        'member_skin_key' => 'basic',
        'profile_birth_date_enabled' => true,
        'profile_birth_date_required' => false,
        'profile_is_adult_enabled' => true,
        'profile_is_adult_required' => false,
        'profile_avatar_enabled' => true,
        'profile_avatar_required' => false,
        'profile_fields_json' => '[]',
        'profile_field_order_json' => '[]',
        'nickname_enabled' => true,
        'nickname_required' => true,
    ],
];
