<?php

return [
    'GET /login' => 'actions/login.php',
    'POST /login' => 'actions/login.php',
    'GET /register' => 'actions/register.php',
    'POST /register' => 'actions/register.php',
    'GET /member/avatar' => 'actions/avatar.php',
    'GET /account' => 'actions/account.php',
    'POST /account' => 'actions/account.php',
    'GET /admin/members' => 'actions/admin-members.php',
    'POST /admin/members' => 'actions/admin-members.php',
    'GET /admin/members/search' => 'actions/admin-member-search.php',
    'GET /admin/members/summary' => 'actions/admin-member-summary.php',
    'GET /admin/members/new' => 'actions/admin-members-new.php',
    'GET /admin/members/edit' => 'actions/admin-members-edit.php',
    'POST /admin/members/save' => 'actions/admin-members-save.php',
    'GET /admin/member-settings' => 'actions/admin-settings.php',
    'POST /admin/member-settings' => 'actions/admin-settings.php',
    'GET /admin/member-groups' => 'actions/admin-groups.php',
    'POST /admin/member-groups' => 'actions/admin-groups.php',
    'GET /admin/member-groups/new' => 'actions/admin-groups-new.php',
    'GET /admin/member-groups/edit' => 'actions/admin-groups-edit.php',
    'POST /admin/member-groups/save' => 'actions/admin-groups-save.php',
    'GET /admin/member-group-rules' => 'actions/admin-group-rules.php',
    'GET /admin/member-group-rules/new' => 'actions/admin-group-rules-new.php',
    'GET /admin/member-group-rules/edit' => 'actions/admin-group-rules-edit.php',
    'POST /admin/member-group-rules/save' => 'actions/admin-group-rules-save.php',
    'POST /admin/member-group-evaluations/account' => 'actions/admin-group-evaluations-account.php',
    'GET /admin/member-group-assignments' => 'actions/admin-group-assignments.php',
    'POST /admin/member-group-assignments/grant' => 'actions/admin-group-assignments-grant.php',
    'POST /admin/member-group-assignments/revoke' => 'actions/admin-group-assignments-revoke.php',
    'POST /admin/member-groups/recalculate' => 'actions/admin-groups.php',
    'GET /account/withdraw' => 'actions/withdraw.php',
    'POST /account/withdraw' => 'actions/withdraw.php',
    'POST /account/email-verification' => 'actions/email-verification-request.php',
    'GET /email/verify' => 'actions/email-verify.php',
    'GET /email/verified' => 'actions/email-verified.php',
    'GET /password/reset' => 'actions/password-reset-request.php',
    'POST /password/reset' => 'actions/password-reset-request.php',
    'GET /password/reset/confirm' => 'actions/password-reset.php',
    'POST /password/reset/confirm' => 'actions/password-reset.php',
    'POST /logout' => 'actions/logout.php',
];
