CREATE TABLE IF NOT EXISTS sr_asset_exchange_policies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    from_module_key VARCHAR(40) NOT NULL,
    to_module_key VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'disabled',
    rate_numerator BIGINT UNSIGNED NOT NULL DEFAULT 1,
    rate_denominator BIGINT UNSIGNED NOT NULL DEFAULT 1,
    min_amount BIGINT UNSIGNED NOT NULL DEFAULT 1,
    max_amount BIGINT UNSIGNED NULL,
    rounding_mode VARCHAR(20) NOT NULL DEFAULT 'floor',
    fee_trigger VARCHAR(20) NOT NULL DEFAULT 'none',
    fee_basis VARCHAR(20) NOT NULL DEFAULT 'to_amount',
    fee_rate_numerator BIGINT UNSIGNED NOT NULL DEFAULT 0,
    fee_rate_denominator BIGINT UNSIGNED NOT NULL DEFAULT 100,
    fee_fixed_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
    fee_min_amount BIGINT UNSIGNED NULL,
    fee_max_amount BIGINT UNSIGNED NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_asset_exchange_policies_pair (from_module_key, to_module_key),
    KEY idx_sr_asset_exchange_policies_status_sort (status, sort_order, id)
);

CREATE TABLE IF NOT EXISTS sr_asset_exchange_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    exchange_group_id VARCHAR(80) NOT NULL,
    policy_id BIGINT UNSIGNED NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    from_module_key VARCHAR(40) NOT NULL,
    to_module_key VARCHAR(40) NOT NULL,
    request_amount BIGINT NOT NULL,
    rate_numerator BIGINT UNSIGNED NOT NULL,
    rate_denominator BIGINT UNSIGNED NOT NULL,
    rounding_mode VARCHAR(20) NOT NULL,
    deposit_amount BIGINT NOT NULL,
    fee_amount BIGINT NOT NULL DEFAULT 0,
    fee_trigger VARCHAR(20) NOT NULL DEFAULT 'none',
    fee_basis VARCHAR(20) NOT NULL DEFAULT 'to_amount',
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(255) NOT NULL DEFAULT '',
    from_transaction_id BIGINT UNSIGNED NULL,
    to_transaction_id BIGINT UNSIGNED NULL,
    fee_transaction_id BIGINT UNSIGNED NULL,
    created_by_account_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_asset_exchange_logs_group (exchange_group_id),
    KEY idx_sr_asset_exchange_logs_account_created (account_id, created_at),
    KEY idx_sr_asset_exchange_logs_policy_created (policy_id, created_at),
    KEY idx_sr_asset_exchange_logs_pair_created (from_module_key, to_module_key, created_at),
    KEY idx_sr_asset_exchange_logs_reexchange (account_id, to_module_key, status, created_at),
    KEY idx_sr_asset_exchange_logs_status_created (status, created_at)
);
