CREATE TABLE IF NOT EXISTS {{SR_TABLE_PREFIX}}coupon_claim_campaigns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_key VARCHAR(60) NOT NULL,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    claim_type VARCHAR(20) NOT NULL DEFAULT 'free',
    price_amount INT UNSIGNED NULL,
    price_currency_code VARCHAR(3) NOT NULL DEFAULT '',
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    issue_expires_in_days INT UNSIGNED NULL,
    issue_expires_at DATETIME NULL,
    total_claim_limit INT UNSIGNED NULL,
    per_account_limit INT UNSIGNED NOT NULL DEFAULT 1,
    visibility VARCHAR(20) NOT NULL DEFAULT 'hidden',
    exposure_surfaces_json TEXT NOT NULL,
    login_required TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_claim_campaigns_key (campaign_key),
    KEY idx_sr_coupon_claim_campaigns_public (status, visibility, starts_at, ends_at, id),
    KEY idx_sr_coupon_claim_campaigns_definition (coupon_definition_id, status, id)
);

CREATE TABLE IF NOT EXISTS {{SR_TABLE_PREFIX}}coupon_claim_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    campaign_id BIGINT UNSIGNED NOT NULL,
    coupon_definition_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    coupon_issue_id BIGINT UNSIGNED NULL,
    claim_source VARCHAR(40) NOT NULL DEFAULT 'coupon_zone',
    source_context_json TEXT NOT NULL,
    payment_reference_module VARCHAR(60) NOT NULL DEFAULT '',
    payment_reference_type VARCHAR(80) NOT NULL DEFAULT '',
    payment_reference_id VARCHAR(120) NOT NULL DEFAULT '',
    asset_reference_module VARCHAR(60) NOT NULL DEFAULT '',
    asset_reference_type VARCHAR(80) NOT NULL DEFAULT '',
    asset_reference_id VARCHAR(120) NOT NULL DEFAULT '',
    dedupe_key VARCHAR(255) NOT NULL,
    dedupe_hash CHAR(64) NOT NULL,
    occupying_account_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'reserved',
    reserved_until DATETIME NULL,
    failure_code VARCHAR(60) NOT NULL DEFAULT '',
    failure_message VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    issued_at DATETIME NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_coupon_claim_logs_dedupe (campaign_id, dedupe_hash),
    UNIQUE KEY uq_sr_coupon_claim_logs_issue (coupon_issue_id),
    UNIQUE KEY uq_sr_coupon_claim_logs_account_once (campaign_id, occupying_account_id),
    KEY idx_sr_coupon_claim_logs_campaign_status (campaign_id, status, reserved_until, id),
    KEY idx_sr_coupon_claim_logs_account (account_id, status, id)
);

UPDATE sr_modules
SET version = '2026.06.001',
    updated_at = NOW()
WHERE module_key = 'coupon';
